import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, test } from "bun:test"
import { createHash } from "node:crypto"

import { jetstream, StorageType } from "@nats-io/jetstream"
import type { NatsConnection } from "@nats-io/nats-core"
import { Objm, type ObjectInfo, type ObjectStore } from "@nats-io/obj"
import { connect } from "@nats-io/transport-node"

import {
  buildServerBinary,
  startNatsServer,
  type NatsHarness,
  type NatsServerBinary,
} from "./NatsHarness.js"

/** The client's own default when a put declares no maximum chunk size. */
const DEFAULT_CHUNK_SIZE = 128 * 1024

/**
 * The independent oracle: Node's SHA-256, base64url with padding restored,
 * under the client's `SHA-256=` prefix. Both sides must agree on the same
 * bytes without sharing an implementation.
 */
const independentDigest = (bytes: Uint8Array): string => {
  const raw = createHash("sha256").update(bytes).digest("base64url")
  const padding = raw.length % 4 === 0 ? "" : "=".repeat(4 - (raw.length % 4))
  return `SHA-256=${raw}${padding}`
}

/**
 * Probe inputs, generated by this LCG rather than hand-typed. They are not
 * fixtures: the root glossary reserves that word for frozen digest pins minted
 * by the side that owns a model, and nothing here pins a model's answer.
 */
const pattern = (length: number, seed: number): Uint8Array => {
  const bytes = new Uint8Array(length)
  let state = seed >>> 0
  for (let index = 0; index < length; index++) {
    state = (state * 1664525 + 1013904223) >>> 0
    bytes[index] = state >>> 24
  }
  return bytes
}

const sameBytes = (left: Uint8Array | null, right: Uint8Array): boolean =>
  left !== null && Buffer.compare(Buffer.from(left), Buffer.from(right)) === 0

/** Reads one object's stream to exhaustion, recording per-read sizes. */
const readSizes = async (store: ObjectStore, name: string): Promise<ReadonlyArray<number>> => {
  const result = await store.get(name)
  if (result === null) throw new Error(`no object named ${name}`)
  const sizes: Array<number> = []
  const reader = result.data.getReader()
  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    if (value !== undefined) sizes.push(value.length)
  }
  await result.error
  return sizes
}

/** Records the message of a refusal instead of asserting through a matcher. */
const refusalOf = async (operation: Promise<unknown>): Promise<string> => {
  try {
    await operation
    return "resolved"
  } catch (error) {
    return String(error).split("\n")[0] ?? ""
  }
}

/**
 * One connection and one fresh bucket, closed however the arm ends.
 *
 * Every arm opened a connection, created a store, wrapped its body in `try`,
 * and closed in `finally` — five copies of one lifecycle. With it here, each
 * arm below owns only its observation.
 */
const probe = async <A>(
  bucket: string,
  observe: (store: ObjectStore, connection: NatsConnection) => Promise<A>,
): Promise<A> => {
  const connection = await connect({ servers: harness!.url })
  try {
    const store = await new Objm(connection).create(bucket, {
      storage: StorageType.File,
      replicas: 1,
    })
    return await observe(store, connection)
  } finally {
    await connection.close()
  }
}

let built: NatsServerBinary
let harness: NatsHarness | undefined

beforeAll(async () => {
  built = await buildServerBinary()
})

afterAll(async () => {
  await built.cleanup()
})

beforeEach(async () => {
  harness = await startNatsServer(built.binary)
})

afterEach(async () => {
  if (harness !== undefined) await harness.stop()
  harness = undefined
})

describe("tenth substrate suite: @nats-io/obj 3.4.0 object-store semantics", () => {
  test("put/get round-trips the bytes and the reported digest is a re-derivable SHA-256", async () => {
    await probe("OBJ_ROUNDTRIP", async (store, connection) => {
      const payload = pattern(1024, 7)
      const info = await store.putBlob({ name: "alpha" }, payload)

      expect(info.size).toBe(1024)
      expect(info.chunks).toBe(1)
      expect(info.deleted).toBe(false)
      expect(info.digest).toBe(independentDigest(payload))
      expect(sameBytes(await store.getBlob("alpha"), payload)).toBe(true)

      // A whole-object read re-derives the digest and refuses on disagreement,
      // so the store is never trusted about content.
      const multiChunk = pattern(2 * DEFAULT_CHUNK_SIZE, 31)
      const tampered = await store.putBlob({ name: "tampered" }, multiChunk)
      await jetstream(connection).publish(
        `$O.OBJ_ROUNDTRIP.C.${tampered.nuid}`,
        new Uint8Array([0, 1, 2]),
      )
      const afterTamper = await store.info("tampered")
      expect(afterTamper?.size).toBe(tampered.size)
      expect(afterTamper?.chunks).toBe(tampered.chunks)
      expect(afterTamper?.digest).toBe(tampered.digest)
      expect(await refusalOf(store.getBlob("tampered"))).toBe(
        "Error: received a corrupt object, digests do not match",
      )

      // The refusal arrives only after every byte, injected bytes included,
      // has already been handed to the reader.
      const result = await store.get("tampered")
      const delivered: Array<number> = []
      let refusal = "none"
      const reader = result!.data.getReader()
      try {
        while (true) {
          const { done, value } = await reader.read()
          if (done) break
          if (value !== undefined) delivered.push(value.length)
        }
      } catch (error) {
        refusal = String(error).split("\n")[0] ?? ""
      }
      expect(delivered).toEqual([DEFAULT_CHUNK_SIZE, DEFAULT_CHUNK_SIZE, 3])
      expect(refusal).toBe("Error: received a corrupt object, digests do not match")

      console.info(
        "SUBSTRATE OBJ TRACE round-trip=bytes-identical digest=SHA-256-base64url-padded oracle=node-crypto client-digest=computed-client-side meta-after-tamper=[size,chunks,digest]-unchanged whole-read=refused delivered-before-refusal=[131072,131072,3]",
      )
    })
  }, 120_000)

  test("chunk count follows the declared maximum and the read stream reproduces the boundaries", async () => {
    await probe("OBJ_CHUNKS", async (store) => {
      const observed: Array<{
        readonly name: string
        readonly size: number
        readonly chunks: number
        readonly maxChunkSize: number | undefined
      }> = []

      for (const [name, size] of [
        ["empty", 0],
        ["minus-one", DEFAULT_CHUNK_SIZE - 1],
        ["exact", DEFAULT_CHUNK_SIZE],
        ["plus-one", DEFAULT_CHUNK_SIZE + 1],
        ["multi", 3 * 1024 * 1024 + 12345],
      ] as const) {
        const payload = pattern(size, size + 1)
        const info = await store.putBlob({ name }, payload)
        observed.push({
          name,
          size: info.size,
          chunks: info.chunks,
          maxChunkSize: info.options?.max_chunk_size,
        })
        expect(info.digest).toBe(independentDigest(payload))
        expect(sameBytes(await store.getBlob(name), payload)).toBe(true)
      }

      expect(observed).toEqual([
        { name: "empty", size: 0, chunks: 0, maxChunkSize: DEFAULT_CHUNK_SIZE },
        { name: "minus-one", size: 131071, chunks: 1, maxChunkSize: DEFAULT_CHUNK_SIZE },
        { name: "exact", size: 131072, chunks: 1, maxChunkSize: DEFAULT_CHUNK_SIZE },
        { name: "plus-one", size: 131073, chunks: 2, maxChunkSize: DEFAULT_CHUNK_SIZE },
        { name: "multi", size: 3158073, chunks: 25, maxChunkSize: DEFAULT_CHUNK_SIZE },
      ])

      // Reads arrive one stored chunk at a time; a zero-length object still
      // yields one empty read before it completes.
      expect(await readSizes(store, "empty")).toEqual([0])
      expect(await readSizes(store, "minus-one")).toEqual([131071])
      expect(await readSizes(store, "exact")).toEqual([131072])
      expect(await readSizes(store, "plus-one")).toEqual([131072, 1])
      const multiSizes = await readSizes(store, "multi")
      expect(multiSizes.length).toBe(25)
      expect(multiSizes.slice(0, 24)).toEqual(Array.from({ length: 24 }, () => 131072))
      expect(multiSizes[24]).toBe(12345)

      // A declared maximum overrides the default and is echoed back in the info.
      const small = await store.putBlob(
        { name: "declared", options: { max_chunk_size: 100 } },
        pattern(1000, 3),
      )
      expect(small.chunks).toBe(10)
      expect(small.options?.max_chunk_size).toBe(100)

      console.info(
        "SUBSTRATE OBJ TRACE default-max-chunk=131072 chunks=[0B:0,131071B:1,131072B:1,131073B:2,3158073B:25] read-boundaries=stored-chunks zero-byte-read=[0] declared-max=100:10-chunks",
      )
    })
  }, 120_000)

  test("the pinned client offers no ranged read and an early-cancelled stream is unverified", async () => {
    await probe("OBJ_RANGED", async (store) => {
      const payload = pattern(3 * DEFAULT_CHUNK_SIZE, 11)
      await store.putBlob({ name: "big" }, payload)

      // The whole reachable surface, enumerated rather than assumed.
      const surface = Object.getOwnPropertyNames(Object.getPrototypeOf(store))
        .filter((member) => !member.startsWith("_") && member !== "constructor")
        .sort()
      expect(surface).toEqual([
        "delete",
        "destroy",
        "get",
        "getBlob",
        "info",
        "init",
        "link",
        "linkStore",
        "list",
        "put",
        "putBlob",
        "rawInfo",
        "seal",
        "status",
        "update",
        "watch",
      ])
      expect(surface.filter((member) => /range|offset|seek|partial|slice/i.test(member))).toEqual([])
      expect(store.get.length).toBe(1)
      expect(store.getBlob.length).toBe(1)

      const result = await store.get("big")
      expect(Object.keys(result!).sort()).toEqual(["data", "error", "info"])

      // The only partial read available is stopping the whole-object stream
      // early; the prefix is served before any digest is derived.
      const reader = result!.data.getReader()
      const first = await reader.read()
      expect(first.done).toBe(false)
      expect(first.value?.length).toBe(DEFAULT_CHUNK_SIZE)
      expect(sameBytes(first.value ?? null, payload.subarray(0, DEFAULT_CHUNK_SIZE))).toBe(true)
      result!.error.catch(() => undefined)
      await reader.cancel()

      // The success path resolves the error promise to undefined, not the
      // documented null; only the zero-size short circuit resolves null.
      const whole = await store.get("big")
      const wholeReader = whole!.data.getReader()
      while (!(await wholeReader.read()).done) {
        // drain
      }
      expect(await whole!.error).toBeUndefined()
      await store.putBlob({ name: "zero" }, new Uint8Array(0))
      const zero = await store.get("zero")
      const zeroReader = zero!.data.getReader()
      expect((await zeroReader.read()).value?.length).toBe(0)
      expect(await zero!.error).toBeNull()

      console.info(
        "SUBSTRATE OBJ TRACE ranged-read=absent get-arity=1 getBlob-arity=1 result-keys=[data,error,info] partial=cancel-only prefix=131072B-unverified error-promise=undefined-on-success,null-on-zero-size",
      )
    })
  }, 120_000)

  test("delete tombstones the metadata and purges the chunks", async () => {
    await probe("OBJ_DELETE", async (store) => {
      const payload = pattern(3 * DEFAULT_CHUNK_SIZE, 5)
      const put = await store.putBlob({ name: "doomed" }, payload)
      expect(put.chunks).toBe(3)
      const before = await store.status()
      expect(before.streamInfo.state.messages).toBe(4)

      const purge = await store.delete("doomed")
      expect(purge.success).toBe(true)
      expect(purge.purged).toBe(3)

      // Chunks are reclaimed; one rolled-up tombstone remains.
      const after = await store.status()
      expect(after.streamInfo.state.messages).toBe(1)
      expect(after.size).toBeLessThan(before.size)

      const tombstone = await store.info("doomed")
      expect(tombstone).not.toBeNull()
      expect({
        deleted: tombstone!.deleted,
        size: tombstone!.size,
        chunks: tombstone!.chunks,
        digest: tombstone!.digest,
        nuid: tombstone!.nuid,
        mtime: tombstone!.mtime,
        revisionAdvanced: tombstone!.revision > put.revision,
      }).toEqual({
        deleted: true,
        size: 0,
        chunks: 0,
        digest: "",
        nuid: put.nuid,
        mtime: put.mtime,
        revisionAdvanced: true,
      })

      expect(await store.get("doomed")).toBeNull()
      expect(await store.getBlob("doomed")).toBeNull()
      expect((await store.list()).map((entry) => entry.name)).toEqual([])
      expect(await refusalOf(store.update("doomed", { description: "revive" }))).toBe(
        "Error: cannot update meta for a deleted object",
      )

      // Deleting a tombstone succeeds with nothing purged; deleting a name
      // that never existed reports failure, and its info is null.
      expect(await store.delete("doomed")).toMatchObject({ success: true, purged: 0 })
      expect(await store.delete("never-existed")).toEqual({ success: false, purged: 0 })
      expect(await store.info("never-existed")).toBeNull()

      // The name is reusable and the reborn object carries a fresh nuid.
      const reborn = await store.putBlob({ name: "doomed" }, pattern(10, 1))
      expect(reborn.deleted).toBe(false)
      expect(reborn.nuid).not.toBe(put.nuid)
      expect(reborn.revision).toBeGreaterThan(tombstone!.revision)

      console.info(
        "SUBSTRATE OBJ TRACE delete=purge(chunks)+rollup(meta) purged=3 messages=4->1 tombstone=[deleted:true,size:0,chunks:0,digest:''] nuid=retained mtime=retained revision=advanced get=null list=omits re-delete=success:true,purged:0 unknown-delete=success:false",
      )
    })
  }, 120_000)

  test("each put mints a fresh nuid and a stream-sequence revision; metadata does not carry over", async () => {
    await probe("OBJ_META", async (store) => {
      const first = pattern(64, 21)
      const one = await store.putBlob({ name: "same", description: "first" }, first)
      const fields = (info: ObjectInfo) => ({
        name: info.name,
        description: info.description,
        size: info.size,
        chunks: info.chunks,
        digest: info.digest,
        nuid: info.nuid,
        mtime: info.mtime,
        revision: info.revision,
        deleted: info.deleted,
      })
      const read = await store.info("same")
      expect(fields(read!)).toEqual(fields(one))

      // Identical bytes re-put under the same name: the digest is stable, but
      // nothing else is. There is no content dedup at this seam.
      const two = await store.putBlob({ name: "same", description: "second" }, first)
      expect(two.digest).toBe(one.digest)
      expect(two.size).toBe(one.size)
      expect(two.nuid).not.toBe(one.nuid)
      expect(two.revision).toBeGreaterThan(one.revision)

      // `mtime` is recomputed on every put and never carried over, but it is a
      // client clock at millisecond resolution, so it is NOT a freshness
      // oracle: two puts inside one millisecond carry the same string. What is
      // asserted is what holds — recomputation and nondecrease.
      expect(two.mtime >= one.mtime).toBe(true)
      expect(new Date(two.mtime).toISOString()).toBe(two.mtime)

      // A put that omits the description clears it rather than inheriting it.
      const three = await store.putBlob({ name: "same" }, pattern(128, 22))
      expect(three.description).toBe("")
      expect(three.size).toBe(128)
      expect((await store.info("same"))?.description).toBe("")
      expect(three.mtime >= two.mtime).toBe(true)

      // The revision is the stream sequence of the meta message: one put of an
      // n-chunk object advances it by n + 1.
      expect([one.revision, two.revision, three.revision]).toEqual([2, 4, 6])
      const big = await store.putBlob({ name: "wide" }, pattern(3 * DEFAULT_CHUNK_SIZE, 9))
      expect(big.chunks).toBe(3)
      expect(big.revision).toBe(three.revision + 4)

      // `previousRevision` is that same stream sequence, and a stale one is
      // refused by the wrong-last-sequence pin.
      const fenced = await store.putBlob({ name: "same" }, pattern(8, 9), {
        previousRevision: three.revision,
      })
      expect(fenced.revision).toBeGreaterThan(big.revision)
      expect(
        await refusalOf(
          store.putBlob({ name: "same" }, pattern(8, 10), { previousRevision: three.revision }),
        ),
      ).toContain("wrong last sequence")

      // `list()` answers a different shape from `info()`: no revision at all.
      const listed = await store.list()
      expect(Object.keys(listed[0]!).sort()).toEqual([
        "bucket",
        "chunks",
        "deleted",
        "description",
        "digest",
        "isUpdate",
        "mtime",
        "name",
        "nuid",
        "options",
        "size",
      ])
      expect(listed.every((entry) => entry.revision === undefined)).toBe(true)
      expect(listed.map((entry) => entry.name).sort()).toEqual(["same", "wide"])

      console.info(
        "SUBSTRATE OBJ TRACE put-same-name=[digest-stable,nuid-fresh,mtime-recomputed-nondecreasing,description-cleared] mtime=client-clock-ms-resolution revision=meta-stream-sequence step=chunks+1 revisions=[2,4,6] previousRevision=stale-refused-wrong-last-sequence list-entry=no-revision-field",
      )
    })
  }, 120_000)
})
