// Code generated by scratch/km-polyglot/kmgen.go from sample-kernel-conformance.ndjson (schema v1).
// DO NOT EDIT.
//
// EXEMPLAR ONLY. Nothing imports this package. It exists to show that a
// schema-v1 kernel-conformance artifact drives a Go type layer
// mechanically. It is a demonstration, not a runtime, and it promotes no
// runtime guarantee: the model's theorems are about the model.

package kmconform

import "fmt"

// Source names the model this table was emitted from.
const (
	Source    = "verify/kernel"
	Generator = "verify/unity emit"
	Format    = 1
)

// DeclKind is the closed universe of declaration kinds. The numeric
// value is the model's rank, so it is wire-stable within a format.
type DeclKind uint8

const (
	KindSchema     DeclKind = 0
	KindProgram    DeclKind = 1
	KindPolicy     DeclKind = 2
	KindCapability DeclKind = 3
	KindLane       DeclKind = 4
	KindAlgebra    DeclKind = 5
	KindIndex      DeclKind = 6
	KindResource   DeclKind = 7
	KindOntology   DeclKind = 8
	KindSchedule   DeclKind = 9
	KindTemplate   DeclKind = 10
	KindLanguage   DeclKind = 11
)

var declKindNames = [...]string{
	"schema",
	"program",
	"policy",
	"capability",
	"lane",
	"algebra",
	"index",
	"resource",
	"ontology",
	"schedule",
	"template",
	"language",
}

func (k DeclKind) String() string {
	if int(k) >= len(declKindNames) {
		return fmt.Sprintf("DeclKind(%d)", uint8(k))
	}
	return declKindNames[k]
}

// DeclKindFromRank is the decode half of the rank. It refuses an
// out-of-range rank rather than saturating.
func DeclKindFromRank(rank uint8) (DeclKind, bool) {
	if int(rank) >= len(declKindNames) {
		return 0, false
	}
	return DeclKind(rank), true
}

// HoleStage is the epistemic stage of a hole, in rising rank order.
type HoleStage uint8

const (
	StageOpened   HoleStage = 0
	StageFilled   HoleStage = 1
	StageDisputed HoleStage = 2
	StageDecided  HoleStage = 3
	StageSealed   HoleStage = 4
)

var holeStageNames = [...]string{
	"opened",
	"filled",
	"disputed",
	"decided",
	"sealed",
}

func (s HoleStage) String() string {
	if int(s) >= len(holeStageNames) {
		return fmt.Sprintf("HoleStage(%d)", uint8(s))
	}
	return holeStageNames[s]
}

// Reached reports whether s is at least target. A hole production
// observes rank only in the reached-at-least direction.
func (s HoleStage) Reached(target HoleStage) bool { return s >= target }

// Applicability marks whether a taught repair is a function of the
// refused candidate alone.
type Applicability uint8

const (
	MachineApplicable Applicability = iota
	Advisory
)

func (a Applicability) String() string {
	if a == MachineApplicable {
		return "machine-applicable"
	}
	return "advisory"
}

// RefusalReason indexes the taught table. The numeric value is this
// table's position, not a model rank; compare by Wire across versions.
type RefusalReason uint8

const (
	ReasonClockRead            RefusalReason = 0
	ReasonAbsenceTrigger       RefusalReason = 1
	ReasonUnfencedDecide       RefusalReason = 2
	ReasonLastWriterWins       RefusalReason = 3
	ReasonUnverifiedRead       RefusalReason = 4
	ReasonCrossSortIdentifier  RefusalReason = 5
	ReasonMintedIdentifier     RefusalReason = 6
	ReasonAmbientQueryInput    RefusalReason = 7
	ReasonForwardReference     RefusalReason = 8
	ReasonSecretCarrier        RefusalReason = 9
	ReasonAbsenceClaim         RefusalReason = 10
	ReasonPastMutation         RefusalReason = 11
	ReasonOffWritReferent      RefusalReason = 12
	ReasonClosureIntrospection RefusalReason = 13
	ReasonAnchoredResolve      RefusalReason = 14
	ReasonUnfilledHole         RefusalReason = 15
)

// Refusal is one row of the taught table: the reason, the law it
// defends, the taught repair, and how the repair may be applied.
// The door never refuses without teaching the legal next move.
type Refusal struct {
	Reason        RefusalReason
	Wire          string
	Law           string
	Repair        string
	Applicability Applicability
}

// RefusalTable is the taught table, in the model's declaration order.
var RefusalTable = [...]Refusal{
	{
		Reason:        0,
		Wire:          "clock-read",
		Law:           "the fold carrier has no clock parameter (f11_query_deterministic)",
		Repair:        "emit the claimed time as a tick fact on an evidence lane; schedule through a declared schedule value",
		Applicability: Advisory,
	},
	{
		Reason:        1,
		Wire:          "absence-trigger",
		Law:           "the trigger grammar is closed at five monotone productions (f10_stability)",
		Repair:        "route acting-on-silence through the deadline seat: a fenced decide fed by tick facts",
		Applicability: Advisory,
	},
	{
		Reason:        2,
		Wire:          "unfenced-decide",
		Law:           "only a fenced token commits (at_most_one_landed_commit)",
		Repair:        "hold the register's token and commit with it; grant and renew are runtime liveness, not grammar",
		Applicability: Advisory,
	},
	{
		Reason:        3,
		Wire:          "last-writer-wins",
		Law:           "cells merge by join under a declared ACI algebra (f1_cell_merge_aci)",
		Repair:        "declare the merge algebra; idempotent join leaves nothing for arrival order to choose",
		Applicability: MachineApplicable,
	},
	{
		Reason:        4,
		Wire:          "unverified-read",
		Law:           "a decode re-derives the digest of what it fetched (verify-on-read)",
		Repair:        "resolve and let the door re-derive; absence is retryable, a mismatch is structural",
		Applicability: MachineApplicable,
	},
	{
		Reason:        5,
		Wire:          "cross-sort-identifier",
		Law:           "tokens are per-register and positions are per-partition; sorts never compare across spaces",
		Repair:        "compare a token only within its register and a position only within its partition",
		Applicability: Advisory,
	},
	{
		Reason:        6,
		Wire:          "minted-identifier",
		Law:           "every identifier is a digest of a declaration or a derivation from one",
		Repair:        "declare the value and use its digest; nothing mints a name",
		Applicability: Advisory,
	},
	{
		Reason:        7,
		Wire:          "ambient-query-input",
		Law:           "a derived read is a function of support and query alone (f11_topk_of_support)",
		Repair:        "read state through a fold at an anchor, and put any seed inside the declared query value",
		Applicability: Advisory,
	},
	{
		Reason:        8,
		Wire:          "forward-reference",
		Law:           "pins name already-admitted digests (c7_pin_well_founded)",
		Repair:        "declare the referent first; the reference graph is a DAG by admission order",
		Applicability: Advisory,
	},
	{
		Reason:        9,
		Wire:          "secret-carrier",
		Law:           "the wire grammar admits no secret position",
		Repair:        "carry credentials in the environmental band as redacted configuration, outside meaning",
		Applicability: Advisory,
	},
	{
		Reason:        10,
		Wire:          "absence-claim",
		Law:           "a local view is a lattice lower bound (cell_absorb_inflationary)",
		Repair:        "claim at-least from a replica, never not-present-anywhere",
		Applicability: Advisory,
	},
	{
		Reason:        11,
		Wire:          "past-mutation",
		Law:           "journals are append-only; anchored resumption survives compaction (compact_below_floor_preserves_resumption)",
		Repair:        "declare a successor value pinning its predecessor; forgetting is fenced compaction above the horizon",
		Applicability: MachineApplicable,
	},
	{
		Reason:        12,
		Wire:          "off-writ-referent",
		Law:           "a declaration's identifiers lie inside the universe its writ pins",
		Repair:        "spawn under a writ that pins the referent, or request the referent into the pinned universe",
		Applicability: Advisory,
	},
	{
		Reason:        13,
		Wire:          "closure-introspection",
		Law:           "a program's identity is its declaration, never its closure bytes",
		Repair:        "reference computation by digest: declare the fold and pin its digest",
		Applicability: Advisory,
	},
	{
		Reason:        14,
		Wire:          "anchored-resolve",
		Law:           "a digest names one value forever, so no anchor can change a resolve",
		Repair:        "drop the anchor; read head-relative state through a fold at an anchor",
		Applicability: MachineApplicable,
	},
	{
		Reason:        15,
		Wire:          "unfilled-hole",
		Law:           "only closed programs execute; a hole is a declared parameter, not a wildcard",
		Repair:        "fill every declared hole; disjoint fills commute, so fill order is free",
		Applicability: Advisory,
	},
}

// Taught returns the row a reason carries. Total by construction: a
// reason without its law and repair cannot exist in this table.
func Taught(r RefusalReason) Refusal { return RefusalTable[r] }

// RefusalByWire resolves a wire reason. Unknown reasons are refused,
// never defaulted.
func RefusalByWire(wire string) (RefusalReason, bool) {
	for i := range RefusalTable {
		if RefusalTable[i].Wire == wire {
			return RefusalReason(i), true
		}
	}
	return 0, false
}

// RefusalError carries a taught refusal as a Go error, so the taught
// table becomes the caller-facing diagnostic vocabulary.
type RefusalError struct{ Refusal Refusal }

func (e RefusalError) Error() string {
	return e.Refusal.Wire + ": " + e.Refusal.Law + " [repair: " + e.Refusal.Repair + "]"
}

// Refuse mints the error for a reason.
func Refuse(r RefusalReason) error { return RefusalError{Taught(r)} }

// ---- Brand types ----
//
// The model brands a digest by the kind of declaration it names, and
// the comparison of two differently branded digests HAS NO TYPE: the
// Lean elaborator refuses it. Go's nearest equivalent is one defined
// type per kind. `KindProgramDigest == KindPolicyDigest` is a compile
// error (mismatched types), which is the enforcement this layer buys.
//
// What it does NOT buy, stated plainly:
//   - an untyped constant compares against any brand (`d == 3` compiles);
//   - an explicit conversion crosses any brand (`PolicyDigest(p)`);
//   - value-level brands (a token's register, a position's partition)
//     cannot be type indices in Go, so they ride as unexported data and
//     the elaborator's refusal becomes a run-time check below.
type SchemaDigest uint64
type ProgramDigest uint64
type PolicyDigest uint64
type CapabilityDigest uint64
type LaneDigest uint64
type AlgebraDigest uint64
type IndexDigest uint64
type ResourceDigest uint64
type OntologyDigest uint64
type ScheduleDigest uint64
type TemplateDigest uint64
type LanguageDigest uint64

// The constructor discipline: a digest is minted only from a resolved
// identifier, never from an arbitrary integer at a call site. Nothing
// mints a name.
func NewSchemaDigest(id uint64) SchemaDigest         { return SchemaDigest(id) }
func NewProgramDigest(id uint64) ProgramDigest       { return ProgramDigest(id) }
func NewPolicyDigest(id uint64) PolicyDigest         { return PolicyDigest(id) }
func NewCapabilityDigest(id uint64) CapabilityDigest { return CapabilityDigest(id) }
func NewLaneDigest(id uint64) LaneDigest             { return LaneDigest(id) }
func NewAlgebraDigest(id uint64) AlgebraDigest       { return AlgebraDigest(id) }
func NewIndexDigest(id uint64) IndexDigest           { return IndexDigest(id) }
func NewResourceDigest(id uint64) ResourceDigest     { return ResourceDigest(id) }
func NewOntologyDigest(id uint64) OntologyDigest     { return OntologyDigest(id) }
func NewScheduleDigest(id uint64) ScheduleDigest     { return ScheduleDigest(id) }
func NewTemplateDigest(id uint64) TemplateDigest     { return TemplateDigest(id) }
func NewLanguageDigest(id uint64) LanguageDigest     { return LanguageDigest(id) }

// Token is register-branded in the model: the register is part of the
// token's TYPE, so a cross-register comparison fails to elaborate. Go
// cannot index a type by a value, so the register rides as unexported
// data and the refusal is a run-time check.
type Token struct {
	register ProgramDigest
	value    uint64
}

// NewToken pins the issuing register at construction.
func NewToken(register ProgramDigest, value uint64) Token {
	return Token{register: register, value: value}
}

// Spend refuses a token presented at a register that did not issue it.
// In the model this is the must-not-compile row cross-register-token.
func (t Token) Spend(register ProgramDigest) (uint64, error) {
	if t.register != register {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	return t.value, nil
}

// LanePartition is the venue-local shard of an evidence stream.
type LanePartition struct {
	Lane  LaneDigest
	Shard uint64
}

// Position is partition-branded in the model. Same story as Token: the
// partition rides as data and the refusal is a run-time check.
type Position struct {
	partition LanePartition
	value     uint64
}

func NewPosition(partition LanePartition, value uint64) Position {
	return Position{partition: partition, value: value}
}

// Compare refuses two positions denominated in different partitions —
// the proven-but-vacuous-bound failure the model gives no syntax.
func (p Position) Compare(other Position) (int, error) {
	if p.partition != other.partition {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	switch {
	case p.value < other.value:
		return -1, nil
	case p.value > other.value:
		return 1, nil
	default:
		return 0, nil
	}
}

// ---- Conformance vectors ----
//
// These are the model's own outputs. A consumer tests its door against
// them verdict for verdict. They check a runtime against the model's
// verdicts; they do not promote model theorems into runtime guarantees.

// EncodingVector is one canonical sentence framing.
type EncodingVector struct {
	Name string
	Act  []uint64
}

var EncodingVectors = []EncodingVector{
	{Name: "lawfulDeclareAct", Act: []uint64{0, 0, 7000051000172, 4}},
	{Name: "resolveSchemaEight", Act: []uint64{1, 0, 8}},
	{Name: "emitLaneOne", Act: []uint64{2, 1, 42}},
	{Name: "joinResourceSix", Act: []uint64{3, 6, 42}},
	{Name: "foldAtGroundAnchor", Act: []uint64{4, 2, 1, 0, 4, 11, 6, 42}},
	{Name: "decideFencedRegisterThree", Act: []uint64{5, 3, 7, 42}},
	{Name: "triggerHoleReachesFilled", Act: []uint64{6, 2, 0, 1, 0, 3}},
	{Name: "spawnPolicyFourFive", Act: []uint64{7, 4, 5}},
}

// AdmissionVector is one planted candidate and the door's verdict.
type AdmissionVector struct {
	Name     string
	Admitted bool
	Reason   string
	Encoded  []uint64
}

var AdmissionVectors = []AdmissionVector{
	{Name: "clockFold", Admitted: false, Reason: "clock-read"},
	{Name: "absenceTrigger", Admitted: false, Reason: "absence-trigger"},
	{Name: "unfencedDecide", Admitted: false, Reason: "unfenced-decide"},
	{Name: "lastWriterJoin", Admitted: false, Reason: "last-writer-wins"},
	{Name: "trustingRead", Admitted: false, Reason: "unverified-read"},
	{Name: "crossRegisterDecide", Admitted: false, Reason: "cross-sort-identifier"},
	{Name: "mintedDeclare", Admitted: false, Reason: "minted-identifier"},
	{Name: "latestRead", Admitted: false, Reason: "ambient-query-input"},
	{Name: "forwardDeclare", Admitted: false, Reason: "forward-reference"},
	{Name: "secretEmit", Admitted: false, Reason: "secret-carrier"},
	{Name: "absenceClaimTrigger", Admitted: false, Reason: "absence-claim"},
	{Name: "pastMutation", Admitted: false, Reason: "past-mutation"},
	{Name: "offWritDeclare", Admitted: false, Reason: "off-writ-referent"},
	{Name: "functionDeclare", Admitted: false, Reason: "closure-introspection"},
	{Name: "anchoredResolve", Admitted: false, Reason: "anchored-resolve"},
	{Name: "holeyEmit", Admitted: false, Reason: "unfilled-hole"},
	{Name: "lawfulDeclare", Admitted: true, Encoded: []uint64{0, 0, 7000051000172, 4}},
}

// MachineApplicableRepairs is the codemod catalog: the repairs that are
// a function of the refused candidate alone.
func MachineApplicableRepairs() []Refusal {
	var out []Refusal
	for _, r := range RefusalTable {
		if r.Applicability == MachineApplicable {
			out = append(out, r)
		}
	}
	return out
}
