/- GENERATED by make_triples.py from fixtures/jcs-rfc8785.json. Do not hand-edit. -/
import EsNumberToString

namespace RQ9

/-- (step-5 triple, expected RFC 8785 string, comment). Zero and the two
    refusal rows are carried separately by the driver. -/
def appendixB : List (Step5 × String × String) := [
  (⟨false, 5, 1, (-323)⟩, "5e-324", "Min positive number"),
  (⟨true, 5, 1, (-323)⟩, "-5e-324", "Min negative number"),
  (⟨false, 17976931348623157, 17, 309⟩, "1.7976931348623157e+308", "Max positive number"),
  (⟨true, 17976931348623157, 17, 309⟩, "-1.7976931348623157e+308", "Max negative number"),
  (⟨false, 9007199254740992, 16, 16⟩, "9007199254740992", "Max positive integer represented by this binary64 value"),
  (⟨true, 9007199254740992, 16, 16⟩, "-9007199254740992", "Max negative integer represented by this binary64 value"),
  (⟨false, 29514790517935283, 17, 21⟩, "295147905179352830000", "Approximately 2^68"),
  (⟨false, 9999999999999997, 16, 23⟩, "9.999999999999997e+22", "Exponent boundary neighbor"),
  (⟨false, 1, 1, 24⟩, "1e+23", "Exponent boundary"),
  (⟨false, 10000000000000001, 17, 24⟩, "1.0000000000000001e+23", "Exponent boundary neighbor"),
  (⟨false, 9999999999999997, 16, 21⟩, "999999999999999700000", "Plain/exponent boundary neighbor"),
  (⟨false, 9999999999999999, 16, 21⟩, "999999999999999900000", "Plain/exponent boundary neighbor"),
  (⟨false, 1, 1, 22⟩, "1e+21", "Plain/exponent boundary"),
  (⟨false, 9999999999999997, 16, (-6)⟩, "9.999999999999997e-7", "Small-number boundary neighbor"),
  (⟨false, 1, 1, (-5)⟩, "0.000001", "Small-number boundary"),
  (⟨false, 3333333333333332, 16, 9⟩, "333333333.3333332", "Long mantissa"),
  (⟨false, 33333333333333325, 17, 9⟩, "333333333.33333325", "Long mantissa"),
  (⟨false, 3333333333333333, 16, 9⟩, "333333333.3333333", "Long mantissa"),
  (⟨false, 3333333333333334, 16, 9⟩, "333333333.3333334", "Long mantissa"),
  (⟨false, 33333333333333343, 17, 9⟩, "333333333.33333343", "Long mantissa"),
  (⟨true, 33333333333333333, 17, (-5)⟩, "-0.0000033333333333333333", "Long mantissa"),
  (⟨false, 14249539237812062, 17, 16⟩, "1424953923781206.2", "Round to even")
]

end RQ9
