#!/usr/bin/env python3
"""Derive ECMAScript step-5 triples (sign, s, k, n) for the RFC 8785 Appendix B rows.

Own-authored for foldlab RQ-9, 2026-08-16. No third-party code.

ECMA-262 10th edition (ES2019) 7.1.12.1 NumberToString step 5 asks for integers
n, k, s with k >= 1, 10^(k-1) <= s < 10^k, the Number value for s * 10^(n-k)
equal to m, and k as small as possible.  This script obtains that triple from
CPython's `repr`, which prints the shortest decimal string that round-trips to
the same binary64 (CPython >= 3.1, David Gay lineage).  The triple is therefore
derived INDEPENDENTLY of the expected strings in fixtures/jcs-rfc8785.json; the
companion renderer then has to reproduce those strings from the triple alone.

Input : ../../../../fixtures/jcs-rfc8785.json  (repo fixture, RFC 8785 Appendix B)
Output: appendix-b-triples.json                (this directory)
        AppendixBVectors.lean                  (generated, never hand-edited)

Usage:  python make_triples.py
"""
from __future__ import annotations

import json
import os
import struct
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURE = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "fixtures", "jcs-rfc8785.json"))
OUT = os.path.join(HERE, "appendix-b-triples.json")


def step5(value: float) -> tuple[bool, int, int, int]:
    """Return (sign, s, k, n) for a finite non-zero binary64, per ES2019 7.1.12.1 step 5."""
    sign = value < 0.0 or (value == 0.0 and struct.pack(">d", value)[0] & 0x80 != 0)
    magnitude = abs(value)
    _, digits, exponent = Decimal(repr(magnitude)).as_tuple()
    s = int("".join(str(d) for d in digits))
    # `s` must not be divisible by 10 (step 5's note); shift trailing zeros into
    # the exponent so the pair (s, exponent) is the canonical step-5 pair.
    while s != 0 and s % 10 == 0:
        s //= 10
        exponent += 1
    k = len(str(s))
    n = k + exponent  # from s * 10^(n-k) == s * 10^exponent
    return sign, s, k, n


def render(sign: bool, s: int, k: int, n: int) -> str:
    """ES2019 7.1.12.1 steps 6-10: render the step-5 triple. Integer/string only."""
    digits = str(s)
    assert len(digits) == k
    if k <= n <= 21:                                   # step 6
        body = digits + "0" * (n - k)
    elif 0 < n <= 21:                                  # step 7
        body = digits[:n] + "." + digits[n:]
    elif -6 < n <= 0:                                  # step 8
        body = "0." + "0" * (-n) + digits
    elif k == 1:                                       # step 9
        body = digits + "e" + ("+" if n - 1 > 0 else "-") + str(abs(n - 1))
    else:                                              # step 10
        body = digits[0] + "." + digits[1:] + "e" + ("+" if n - 1 > 0 else "-") + str(abs(n - 1))
    return ("-" if sign else "") + body


def main() -> int:
    corpus = json.load(open(FIXTURE, encoding="utf-8"))
    rows, failures = [], []
    for row in corpus["numbers"]:
        bits = int(row["ieee754"], 16)
        value = struct.unpack(">Q", struct.pack(">Q", bits))[0]
        value = struct.unpack(">d", struct.pack(">Q", bits))[0]
        if row["encoded"] is None:                     # NaN / Infinity: JCS must refuse
            rows.append({"ieee754": row["ieee754"], "comment": row["comment"], "refuse": True})
            continue
        if value == 0.0:                               # ES step 2 short-circuits both zeros
            rows.append({"ieee754": row["ieee754"], "comment": row["comment"],
                         "zero": True, "expected": row["encoded"]})
            got = "0"
        else:
            sign, s, k, n = step5(value)
            got = render(sign, s, k, n)
            rows.append({"ieee754": row["ieee754"], "comment": row["comment"],
                         "sign": sign, "s": str(s), "k": k, "n": n, "expected": row["encoded"]})
        if got != row["encoded"]:
            failures.append((row["ieee754"], got, row["encoded"]))
        # independent round-trip check on the triple's own rendering
        if not row.get("zero") and float(got) != value:
            failures.append((row["ieee754"], f"round-trip {got}", repr(value)))

    json.dump({"_provenance": {
        "generator": "docs/research/reference/rq9-rfc8785-numbers/make_triples.py",
        "input": "fixtures/jcs-rfc8785.json (RFC 8785 Appendix B)",
        "step5_source": "CPython repr (shortest round-trip); NOT the fixture's expected strings",
        "generated": "2026-08-16",
    }, "rows": rows}, open(OUT, "w", encoding="utf-8"), indent=2)

    lean = [
        "/- GENERATED by make_triples.py from fixtures/jcs-rfc8785.json. Do not hand-edit. -/",
        "import EsNumberToString",
        "",
        "namespace RQ9",
        "",
        "/-- (step-5 triple, expected RFC 8785 string, comment). Zero and the two",
        "    refusal rows are carried separately by the driver. -/",
        "def appendixB : List (Step5 × String × String) := [",
    ]
    body = []
    for row in rows:
        if row.get("refuse") or row.get("zero"):
            continue
        body.append(
            '  (⟨{sign}, {s}, {k}, {n}⟩, "{exp}", "{c}")'.format(
                sign="true" if row["sign"] else "false",
                s=row["s"], k=row["k"],
                n=("({})".format(row["n"]) if row["n"] < 0 else str(row["n"])),
                exp=row["expected"], c=row["comment"]))
    lean.append(",\n".join(body))
    lean += ["]", "", "end RQ9", ""]
    with open(os.path.join(HERE, "AppendixBVectors.lean"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lean))

    print(f"rows={len(rows)} failures={len(failures)}")
    for f in failures:
        print("  MISMATCH", f)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
