/- The pure, total prose projection. Layout decisions live only here. -/
import Projections.Ast
import Lean.Data.Format

namespace Projections.Prose

open Std

private def lines (parts : List Format) : Format :=
  Format.joinSep parts Format.line

private def renderDoc (sentence : DocSentence) : Format :=
  lines
    [ s!"## `{sentence.target}`"
    , ""
    , "Plain register:"
    , ""
    , sentence.plain
    , ""
    , "Algebraic register:"
    , ""
    , s!"`{sentence.algebraic}`" ]

private def renderRefusal (row : RefusalRow) : Format :=
  let applicability := row.applicability.getD "advisory"
  lines
    [ s!"### `{row.reason}`"
    , ""
    , s!"- Law: {row.law}"
    , s!"- Repair: {row.repair}"
    , s!"- Applicability: {applicability}"
    , s!"- Plain: {row.plain}"
    , s!"- Algebraic: `{row.algebraic}`" ]

/-- Render the prose page as a deterministic `Format` value. -/
def render (ast : ProjectionAst) : Format :=
  let header := lines
    [ "# Projection language"
    , ""
    , "Generated by `lake exe projections --target=prose --names=<manifest>`."
    , "The manifest selects declarations; Lean's environment supplies every shape and docstring."
    , ""
    , "" ]
  let docs := Format.joinSep (ast.docs.map renderDoc) (Format.line ++ Format.line)
  let refusals :=
    if ast.refusals.isEmpty then
      (Format.nil)
    else
      Format.line ++ Format.line ++ "## Taught refusals" ++
        Format.line ++ Format.line ++
        Format.joinSep (ast.refusals.map renderRefusal) (Format.line ++ Format.line)
  header ++ docs ++ refusals

/-- Pin the physical layout width even though this printer uses hard line breaks. -/
def renderString (ast : ProjectionAst) : String :=
  Format.pretty (render ast) 100 ++ "\n"

end Projections.Prose
