// Command streamfix generates the cross-language wall fixture for the stream
// lane, ONCE (P2a tradition: generated by the Go side, frozen, and the TS
// side must reproduce every digest byte-identically or a port has drifted —
// which is a finding to investigate, not a constant to update).
//
//	cd go && go run ./cmd/streamfix > ../packages/mech/fixtures/stream-wall.json
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"

	"foldlab/stream"
)

func ev(s string, seq uint64, payload string) stream.Event {
	return stream.Event{Stream: s, Seq: seq, Payload: []byte(payload)}
}

func main() {
	alpha := []stream.Event{ev("alpha", 1, "a=1"), ev("alpha", 2, "b=2"), ev("alpha", 3, "a=3")}
	beta := []stream.Event{ev("beta", 1, "c=4"), ev("beta", 2, "a=5")}
	sources := map[string][]stream.Event{"alpha": alpha, "beta": beta}

	fact := stream.MergeFact{Picks: []stream.Pick{
		{Stream: "alpha", Seq: 1}, {Stream: "beta", Seq: 1}, {Stream: "alpha", Seq: 2},
		{Stream: "beta", Seq: 2}, {Stream: "alpha", Seq: 3},
	}}
	merged, err := stream.ApplyMerge(fact, sources)
	if err != nil {
		panic(err)
	}
	state, err := stream.FoldKV(merged)
	if err != nil {
		panic(err)
	}
	compacted, err := stream.Compact(stream.MergeSeed(), merged, 2)
	if err != nil {
		panic(err)
	}

	root := stream.StreamSeed("session")
	st := stream.Store{}
	trunk := st.Put(stream.Segment{Parent: root, Events: []stream.Event{
		ev("session", 1, "a=1"), ev("session", 2, "b=2"),
	}})
	childA := st.Put(stream.Segment{Parent: trunk, Events: []stream.Event{ev("session", 3, "a=9")}})
	childB := st.Put(stream.Segment{Parent: trunk, Events: []stream.Event{ev("session", 3, "b=7")}})

	frame, err := stream.GzipEvents(alpha)
	if err != nil {
		panic(err)
	}

	out := map[string]any{
		"_provenance": "generated once by go/cmd/streamfix (go run ./cmd/streamfix); frozen. " +
			"Regeneration requires a stated reason in docs/primitives/MECH-attempts.md.",
		"alphaHead":        stream.HeadFrom(stream.StreamSeed("alpha"), alpha).Hex(),
		"betaHead":         stream.HeadFrom(stream.StreamSeed("beta"), beta).Hex(),
		"mergeFactDigest":  stream.FactDigest(fact).Hex(),
		"mergedHead":       stream.HeadFrom(stream.MergeSeed(), merged).Hex(),
		"foldStateDigest":  state.StateDigest().Hex(),
		"compactionBase":   compacted.Base.Hex(),
		"compactionState":  compacted.State.StateDigest().Hex(),
		"compactionTail":   len(compacted.Tail),
		"forkTrunkHead":    trunk.Hex(),
		"forkChildAHead":   childA.Hex(),
		"forkChildBHead":   childB.Hex(),
		"gzipAlphaBase64":  base64.StdEncoding.EncodeToString(frame),
		"gzipAlphaEncoded": len(frame),
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(out); err != nil {
		panic(err)
	}
	fmt.Fprintln(os.Stderr, "stream-wall fixture written to stdout")
}
