// Code generated by cmd/kmgen from ../../packages/plait/fixtures/kernel-conformance.ndjson. DO NOT EDIT.
//
// Every table below is the model's, read out of the conformance corpus and
// written into Go mechanically. Edit the model, re-emit the corpus, re-run
// the generator; editing this file forks the model instead.
//
// What these tables are, and are not: they carry the MODEL'S VERDICTS. They
// do not promote the model's theorems into guarantees about any running
// system. A conforming consumer refuses the same candidates for the same
// reasons and encodes the same acts the same way, and nothing more than that
// should be read into a green conformance run.

package kmconform

import "fmt"

// The provenance of the tables in this file. Display data: no behaviour
// branches on it.
const (
	Source       = "verify/kernel"
	Generator    = "verify/unity emit"
	CorpusFormat = 2
)

// DeclKind is the closed universe of declaration kinds. The numeric value
// is the model's rank, so it is wire-stable within a format.
type DeclKind uint8

const (
	KindSchema     DeclKind = 0
	KindProgram    DeclKind = 1
	KindPolicy     DeclKind = 2
	KindCapability DeclKind = 3
	KindLane       DeclKind = 4
	KindAlgebra    DeclKind = 5
	KindIndex      DeclKind = 6
	KindResource   DeclKind = 7
	KindOntology   DeclKind = 8
	KindSchedule   DeclKind = 9
	KindTemplate   DeclKind = 10
	KindLanguage   DeclKind = 11
)

var declKindNames = [...]string{
	"schema",
	"program",
	"policy",
	"capability",
	"lane",
	"algebra",
	"index",
	"resource",
	"ontology",
	"schedule",
	"template",
	"language",
}

func (k DeclKind) String() string {
	if int(k) >= len(declKindNames) {
		return fmt.Sprintf("DeclKind(%d)", uint8(k))
	}
	return declKindNames[k]
}

// DeclKindFromRank is the decode half of the rank. An out-of-range rank is
// refused, never saturated: a decoder that clamps turns a wire defect into a
// plausible wrong answer.
func DeclKindFromRank(rank uint8) (DeclKind, bool) {
	if int(rank) >= len(declKindNames) {
		return 0, false
	}
	return DeclKind(rank), true
}

// DeclKindByName resolves a wire name. Unknown names are refused.
func DeclKindByName(name string) (DeclKind, bool) {
	for rank, known := range declKindNames {
		if known == name {
			return DeclKind(rank), true
		}
	}
	return 0, false
}

// HoleStage is the epistemic stage of a hole, in rising rank order.
type HoleStage uint8

const (
	StageOpened   HoleStage = 0
	StageFilled   HoleStage = 1
	StageDisputed HoleStage = 2
	StageDecided  HoleStage = 3
	StageSealed   HoleStage = 4
)

var holeStageNames = [...]string{
	"opened",
	"filled",
	"disputed",
	"decided",
	"sealed",
}

func (s HoleStage) String() string {
	if int(s) >= len(holeStageNames) {
		return fmt.Sprintf("HoleStage(%d)", uint8(s))
	}
	return holeStageNames[s]
}

// Reached reports whether s is at least target. A hole production observes
// rank only in the reached-at-least direction.
func (s HoleStage) Reached(target HoleStage) bool { return s >= target }

// HoleStageFromRank refuses an out-of-range rank rather than saturating.
func HoleStageFromRank(rank uint8) (HoleStage, bool) {
	if int(rank) >= len(holeStageNames) {
		return 0, false
	}
	return HoleStage(rank), true
}

// Applicability marks whether a taught repair is a function of the refused
// candidate alone. The machine-applicable half is what tells an agent it may
// apply the repair without asking, so the mark has to survive to the caller
// or the taught table is only prose.
type Applicability uint8

const (
	MachineApplicable Applicability = iota
	Advisory
)

func (a Applicability) String() string {
	if a == MachineApplicable {
		return "machine-applicable"
	}
	return "advisory"
}

// RefusalReason indexes the taught table. The numeric value is this table's
// position, which is the model's RefusalReason declaration order; compare by
// Wire when crossing a version boundary.
type RefusalReason uint8

const (
	ReasonClockRead            RefusalReason = 0
	ReasonAbsenceTrigger       RefusalReason = 1
	ReasonUnfencedDecide       RefusalReason = 2
	ReasonLastWriterWins       RefusalReason = 3
	ReasonUnverifiedRead       RefusalReason = 4
	ReasonCrossSortIdentifier  RefusalReason = 5
	ReasonMintedIdentifier     RefusalReason = 6
	ReasonAmbientQueryInput    RefusalReason = 7
	ReasonForwardReference     RefusalReason = 8
	ReasonSecretCarrier        RefusalReason = 9
	ReasonAbsenceClaim         RefusalReason = 10
	ReasonPastMutation         RefusalReason = 11
	ReasonOffWritReferent      RefusalReason = 12
	ReasonClosureIntrospection RefusalReason = 13
	ReasonAnchoredResolve      RefusalReason = 14
	ReasonUnfilledHole         RefusalReason = 15
)

// Refusal is one row of the taught table: the reason, the law it defends, the
// taught repair, and how the repair may be applied. The door never refuses
// without teaching the legal next move, so no field here is optional.
type Refusal struct {
	Reason        RefusalReason
	Wire          string
	Law           string
	Repair        string
	Applicability Applicability
}

// RefusalTable is the taught table in the model's declaration order.
var RefusalTable = [...]Refusal{
	{
		Reason:        0,
		Wire:          "clock-read",
		Law:           "the fold carrier has no clock parameter (f11_query_deterministic)",
		Repair:        "emit the claimed time as a tick fact on an evidence lane; schedule through a declared schedule value",
		Applicability: Advisory,
	},
	{
		Reason:        1,
		Wire:          "absence-trigger",
		Law:           "the trigger grammar is closed at five monotone productions (f10_stability)",
		Repair:        "route acting-on-silence through the deadline seat: a fenced decide fed by tick facts",
		Applicability: Advisory,
	},
	{
		Reason:        2,
		Wire:          "unfenced-decide",
		Law:           "only a fenced token commits (at_most_one_landed_commit)",
		Repair:        "hold the register's token and commit with it; grant and renew are runtime liveness, not grammar",
		Applicability: Advisory,
	},
	{
		Reason:        3,
		Wire:          "last-writer-wins",
		Law:           "cells merge by join under a declared ACI algebra (f1_cell_merge_aci)",
		Repair:        "declare the merge algebra; idempotent join leaves nothing for arrival order to choose",
		Applicability: MachineApplicable,
	},
	{
		Reason:        4,
		Wire:          "unverified-read",
		Law:           "a decode re-derives the digest of what it fetched (verify-on-read)",
		Repair:        "resolve and let the door re-derive; absence is retryable, a mismatch is structural",
		Applicability: MachineApplicable,
	},
	{
		Reason:        5,
		Wire:          "cross-sort-identifier",
		Law:           "tokens are per-register and positions are per-partition; sorts never compare across spaces",
		Repair:        "compare a token only within its register and a position only within its partition",
		Applicability: Advisory,
	},
	{
		Reason:        6,
		Wire:          "minted-identifier",
		Law:           "every identifier is a digest of a declaration or a derivation from one",
		Repair:        "declare the value and use its digest; nothing mints a name",
		Applicability: Advisory,
	},
	{
		Reason:        7,
		Wire:          "ambient-query-input",
		Law:           "a derived read is a function of support and query alone (f11_topk_of_support)",
		Repair:        "read state through a fold at an anchor, and put any seed inside the declared query value",
		Applicability: Advisory,
	},
	{
		Reason:        8,
		Wire:          "forward-reference",
		Law:           "pins name already-admitted digests (c7_pin_well_founded)",
		Repair:        "declare the referent first; the reference graph is a DAG by admission order",
		Applicability: Advisory,
	},
	{
		Reason:        9,
		Wire:          "secret-carrier",
		Law:           "the wire grammar admits no secret position",
		Repair:        "carry credentials in the environmental band as redacted configuration, outside meaning",
		Applicability: Advisory,
	},
	{
		Reason:        10,
		Wire:          "absence-claim",
		Law:           "a local view is a lattice lower bound (cell_absorb_inflationary)",
		Repair:        "claim at-least from a replica, never not-present-anywhere",
		Applicability: Advisory,
	},
	{
		Reason:        11,
		Wire:          "past-mutation",
		Law:           "journals are append-only; anchored resumption survives compaction (compact_below_floor_preserves_resumption)",
		Repair:        "declare a successor value pinning its predecessor; forgetting is fenced compaction above the horizon",
		Applicability: MachineApplicable,
	},
	{
		Reason:        12,
		Wire:          "off-writ-referent",
		Law:           "a declaration's identifiers lie inside the universe its writ pins",
		Repair:        "spawn under a writ that pins the referent, or request the referent into the pinned universe",
		Applicability: Advisory,
	},
	{
		Reason:        13,
		Wire:          "closure-introspection",
		Law:           "a program's identity is its declaration, never its closure bytes",
		Repair:        "reference computation by digest: declare the fold and pin its digest",
		Applicability: Advisory,
	},
	{
		Reason:        14,
		Wire:          "anchored-resolve",
		Law:           "a digest names one value forever, so no anchor can change a resolve",
		Repair:        "drop the anchor; read head-relative state through a fold at an anchor",
		Applicability: MachineApplicable,
	},
	{
		Reason:        15,
		Wire:          "unfilled-hole",
		Law:           "only closed programs execute; a hole is a declared parameter, not a wildcard",
		Repair:        "fill every declared hole; disjoint fills commute, so fill order is free",
		Applicability: Advisory,
	},
}

// Taught returns the row a reason carries. Total by construction: a reason
// without its law and its repair cannot exist in this table.
func Taught(r RefusalReason) Refusal { return RefusalTable[r] }

// RefusalByWire resolves a wire reason. Unknown reasons are refused, never
// defaulted to a neighbouring row.
func RefusalByWire(wire string) (RefusalReason, bool) {
	for index := range RefusalTable {
		if RefusalTable[index].Wire == wire {
			return RefusalReason(index), true
		}
	}
	return 0, false
}

// RefusalError carries a taught refusal as a Go error, so the model's taught
// table becomes this package's caller-facing diagnostic vocabulary rather
// than a lookup a caller has to remember to perform.
type RefusalError struct{ Refusal Refusal }

func (e RefusalError) Error() string {
	return e.Refusal.Wire + ": " + e.Refusal.Law + " [repair: " + e.Refusal.Repair + "]"
}

// Refuse mints the error for a reason.
func Refuse(r RefusalReason) error { return RefusalError{Taught(r)} }

// MachineApplicableRepairs is the codemod catalog: the repairs that are a
// function of the refused candidate alone.
func MachineApplicableRepairs() []Refusal {
	catalog := make([]Refusal, 0, len(RefusalTable))
	for _, row := range RefusalTable {
		if row.Applicability == MachineApplicable {
			catalog = append(catalog, row)
		}
	}
	return catalog
}

// ---- Brand types ----
//
// The model brands a digest by the kind of declaration it names, and the
// comparison of two differently branded digests HAS NO TYPE: the Lean
// elaborator refuses it, so there is nothing to write. Go's nearest
// equivalent is one defined type per kind, which makes the cross-kind
// comparison a compile error.
//
// What the defined type does NOT buy, stated plainly rather than left for a
// reader to discover:
//
//   - an untyped constant adopts any brand, so `d == 3` compiles;
//   - an explicit conversion crosses any brand, silently and always;
//   - a value-level brand (the register that issued a token) has no type to
//     become, because Go has no dependent types, so it rides as data and the
//     elaborator's refusal becomes the run-time check below.
//
// The first two are closed mechanically by foldlab/brandlint, which reads the
// //foldlab:brand directives on these declarations. The third is not closed
// at all: a caller who drops the returned error gets nothing.

//foldlab:brand schema
type SchemaDigest uint64

//foldlab:brand program
type ProgramDigest uint64

//foldlab:brand policy
type PolicyDigest uint64

//foldlab:brand capability
type CapabilityDigest uint64

//foldlab:brand lane
type LaneDigest uint64

//foldlab:brand algebra
type AlgebraDigest uint64

//foldlab:brand index
type IndexDigest uint64

//foldlab:brand resource
type ResourceDigest uint64

//foldlab:brand ontology
type OntologyDigest uint64

//foldlab:brand schedule
type ScheduleDigest uint64

//foldlab:brand template
type TemplateDigest uint64

//foldlab:brand language
type LanguageDigest uint64

// The constructor discipline: a digest is minted from a resolved identifier
// through a named function, never conjured from an integer at a call site.
// Nothing mints a name.
func NewSchemaDigest(id uint64) SchemaDigest         { return SchemaDigest(id) }
func NewProgramDigest(id uint64) ProgramDigest       { return ProgramDigest(id) }
func NewPolicyDigest(id uint64) PolicyDigest         { return PolicyDigest(id) }
func NewCapabilityDigest(id uint64) CapabilityDigest { return CapabilityDigest(id) }
func NewLaneDigest(id uint64) LaneDigest             { return LaneDigest(id) }
func NewAlgebraDigest(id uint64) AlgebraDigest       { return AlgebraDigest(id) }
func NewIndexDigest(id uint64) IndexDigest           { return IndexDigest(id) }
func NewResourceDigest(id uint64) ResourceDigest     { return ResourceDigest(id) }
func NewOntologyDigest(id uint64) OntologyDigest     { return OntologyDigest(id) }
func NewScheduleDigest(id uint64) ScheduleDigest     { return ScheduleDigest(id) }
func NewTemplateDigest(id uint64) TemplateDigest     { return TemplateDigest(id) }
func NewLanguageDigest(id uint64) LanguageDigest     { return LanguageDigest(id) }

// BrandTypeNames lists the brands this package declares, so a lint that
// runs over a CONSUMER of this package can be told the brand set without
// re-deriving it from the corpus.
var BrandTypeNames = []string{
	"SchemaDigest",
	"ProgramDigest",
	"PolicyDigest",
	"CapabilityDigest",
	"LaneDigest",
	"AlgebraDigest",
	"IndexDigest",
	"ResourceDigest",
	"OntologyDigest",
	"ScheduleDigest",
	"TemplateDigest",
	"LanguageDigest",
}

// ---- Value-level brands ----
//
// In the model a token's register and a position's partition are part of the
// TYPE, so a cross-register spend and a cross-partition compare fail to
// elaborate. Go cannot index a type by a value, so the brand rides as
// unexported data and the refusal moves from compile time to run time. That
// is a real loss and not a workaround that recovers the property.

// Token is a lease, meaningful only at the register that issued it.
type Token struct {
	register ProgramDigest
	value    uint64
}

// NewToken pins the issuing register at construction, so a token with no
// register cannot be built.
func NewToken(register ProgramDigest, value uint64) Token {
	return Token{register: register, value: value}
}

// Register reports which register issued the token.
func (t Token) Register() ProgramDigest { return t.register }

// Spend refuses a token presented at a register that did not issue it. In
// the model this refusal is a type error; here it is an error value, and a
// caller who discards it has the guarantee of neither.
func (t Token) Spend(register ProgramDigest) (uint64, error) {
	if t.register != register {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	return t.value, nil
}

// LanePartition is the venue-local shard of an evidence stream.
type LanePartition struct {
	Lane  LaneDigest
	Shard uint64
}

// Position is a journal position, meaningful only within its partition.
type Position struct {
	partition LanePartition
	value     uint64
}

// NewPosition pins the partition at construction.
func NewPosition(partition LanePartition, value uint64) Position {
	return Position{partition: partition, value: value}
}

// Partition reports the partition a position is denominated in.
func (p Position) Partition() LanePartition { return p.partition }

// Compare refuses two positions denominated in different partitions — the
// proven-but-vacuous comparison the model gives no syntax for.
func (p Position) Compare(other Position) (int, error) {
	if p.partition != other.partition {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	switch {
	case p.value < other.value:
		return -1, nil
	case p.value > other.value:
		return 1, nil
	default:
		return 0, nil
	}
}

// TypeNames is the closed type list in the model's declaration order.
var TypeNames = []string{
	"DeclKind",
	"Digest",
	"Value",
	"StateLabel",
	"Petname",
	"Token",
	"LanePartition",
	"Position",
	"AnchorFact",
	"HoleStage",
	"KTriggerPredicate",
	"Act",
	"RawArg",
	"CandidateAnchor",
	"TokenClaim",
	"MergeStrategy",
	"CandidatePredicate",
	"CandidateAct",
	"RefusalReason",
	"Refusal",
	"Applicability",
	"Door",
}

// ---- Docstrings ----
//
// The model's own prose, extracted from its environment and carried here
// verbatim. It is the text a generated schema annotation publishes as a
// parameter description, which is how a sentence written once in the model
// reaches an agent with no human in the path — and why a hand-edited copy is
// a wrong answer rather than a typo.

// DocEntry is one type's docstring.
type DocEntry struct {
	Name string
	Doc  string
}

// DocTable is the doc group in type declaration order.
var DocTable = []DocEntry{
	{Name: "DeclKind", Doc: "The closed universe of declaration kinds. One brand per kind: a\ndigest is always the digest of a declaration of a known kind. "},
	{Name: "Digest", Doc: "A content address branded by the declaration kind it names. Digests\nare modeled as identity labels; that a real digest is a hash over\none canonical byte form stays in the trusted base. A digest of one\nkind never compares with a digest of another: the comparison has no\ntype, which is the referent-pinning discipline carried by the sort\nsystem itself. "},
	{Name: "Value", Doc: "An immutable value at its canonical byte form, modeled as an opaque\nidentity label. Canonical-byte identity (one value, one byte form)\nis the certifier's own wall and is not restated here. "},
	{Name: "StateLabel", Doc: "The digest of a fold state: a value identity, never a declaration\nidentity. Its own sort keeps it out of every declaration-digest\nposition. "},
	{Name: "Petname", Doc: "A human-facing petname. Naming, never identity: no operation in this\npackage derives a digest from a petname, because resolution is a\nhead-relative read served by a fold, outside the identity plane. "},
	{Name: "Token", Doc: "A fencing token, meaningful only within the register that issued\nit. The register is part of the token's type: a cross-register\ncomparison fails to elaborate, so the proven-but-vacuous-bound\nfailure (two sides of a comparison denominated in different spaces)\nhas no syntax. "},
	{Name: "LanePartition", Doc: "A lane partition: the venue-local shard of an evidence stream. "},
	{Name: "Position", Doc: "A journal position, meaningful only within its partition. As with\ntokens, the space rides the type. "},
	{Name: "AnchorFact", Doc: "An anchor fact: `(fold digest, partition) -> (floor, state, head)`.\nA fact, not a cache -- the resume coordinate every head-relative\nread carries. The fold digest and partition are part of the type:\nan anchor replays nowhere but at its own fold and partition. "},
	{Name: "HoleStage", Doc: "The epistemic stages of a hole, in rising rank order. `opened` is\nthe protocol stage named open; the language keyword forces the\nspelling. "},
	{Name: "KTriggerPredicate", Doc: "The closed trigger grammar at kernel sorts: exactly the five\nmonotone productions. Every production reads its component upward\n(presence, reached-at-least, landed, advanced-past), so stability\nunder growth is a property of the grammar's shape. "},
	{Name: "Act", Doc: "One lawful kernel sentence: the eight generators, each constructor\ndemanding exactly the sorts its licensing law names.\n`resolve` is anchor-free because a digest names one value forever;\nevery head-relative read is `fold` at an anchor -- the\nimmutable/head-relative split carried by the constructors\nthemselves. `decide` is commit-with-token: the token's type pins\nthe register, so an unfenced or cross-register commit has no\nderivation. "},
	{Name: "RawArg", Doc: "A raw argument atom. The lawful atoms are digest references and\nliterals; holes are lawful in program declarations and refused in a\nsingle sentence; every other atom is an unlawful shape kept\nspellable so the door's refusal of it is demonstrable. "},
	{Name: "CandidateAnchor", Doc: "A candidate anchor: the raw spelling of a resume coordinate, its\nfold carried as data rather than as a type index -- which is exactly\nwhat lets a cross-fold anchor be spelled and refused. "},
	{Name: "TokenClaim", Doc: "A raw token claim: the register the claimant believes the token\nbelongs to, carried as data so a cross-register claim is spellable\nand refused. "},
	{Name: "MergeStrategy", Doc: "A candidate merge strategy. The lawful strategy names a declared\nmerge algebra; last-writer-wins is spellable here and refused at\nthe door, because no such carrier exists in the fabric. "},
	{Name: "CandidatePredicate", Doc: "The candidate trigger grammar: the five lawful productions plus the\nshapes the closed grammar deliberately cannot carry -- absence,\nnegation, deadline, and the not-present-anywhere claim a local\nreplica can never ground. "},
	{Name: "CandidateAct", Doc: "The raw candidate grammar. Every generator is spellable, and so is\nevery unlawful shape: an anchored resolve, a trusted read, an\nunfenced or cross-register decide, a last-writer-wins join, an\nunanchored latest read, and an in-place mutation of the past. "},
	{Name: "RefusalReason", Doc: "The closed refusal reasons of the kernel door. "},
	{Name: "Refusal", Doc: "A structural refusal: the reason, the law it defends, and the\ntaught repair. Refusal parity as data: the door never refuses\nwithout teaching the legal next move. "},
	{Name: "Applicability", Doc: "How a taught repair may be applied. A repair is machine-applicable\nexactly when the lawful rewrite is a function of the refused\ncandidate alone -- an agent may apply it mechanically, with no new\ninformation; it is advisory when the repair needs something the\ncandidate does not carry (a token to hold, a value to declare, an\nauthority to request). The Rust diagnostic discipline, adopted by\nthe operator's ruling. "},
	{Name: "Door", Doc: "The admission context: the already-admitted catalog and the\nuniverse of referents the acting writ pins. "},
}

// DocFor resolves a type's docstring. A type without one is reported as
// absent rather than as an empty string, so a caller cannot render a blank
// description and believe it is the model's.
func DocFor(name string) (string, bool) {
	for _, entry := range DocTable {
		if entry.Name == name {
			return entry.Doc, true
		}
	}
	return "", false
}

// ---- Conformance vectors ----
//
// The model's own outputs. A consumer tests its door against them verdict for
// verdict. They check an implementation against the model's verdicts; they do
// not promote the model's theorems into runtime guarantees.

// EncodingVector is one canonical sentence framing.
type EncodingVector struct {
	Name string
	Act  []uint64
}

// EncodingVectors is the encoding group in corpus order.
//
// The wire number domain is the unbounded non-negative integers and the
// parser reads it at arbitrary precision. This table is a checked-width
// convenience: kmgen REFUSES to emit a vector that does not fit a uint64
// rather than truncating one, so a corpus that outgrows the width fails
// generation loudly instead of shipping a rounded act.
var EncodingVectors = []EncodingVector{
	{Name: "lawful-declare", Act: []uint64{0, 0, 7000051000172, 4}},
	{Name: "resolve-schema", Act: []uint64{1, 0, 8}},
	{Name: "emit-lane", Act: []uint64{2, 1, 42}},
	{Name: "join-cell", Act: []uint64{3, 6, 42}},
	{Name: "fold-at-anchor", Act: []uint64{4, 2, 1, 0, 4, 11, 6, 13}},
	{Name: "decide-fenced", Act: []uint64{5, 3, 7, 42}},
	{Name: "trigger-evidence-appears", Act: []uint64{6, 0, 1, 17, 0, 3}},
	{Name: "trigger-cell-reaches", Act: []uint64{6, 1, 6, 23, 0, 3}},
	{Name: "trigger-hole-reaches", Act: []uint64{6, 2, 0, 3, 0, 3}},
	{Name: "trigger-outcome-landed", Act: []uint64{6, 3, 3, 0, 0, 3}},
	{Name: "trigger-head-advanced-past", Act: []uint64{6, 4, 1, 0, 6, 3}},
	{Name: "spawn-under-writ", Act: []uint64{7, 4, 5}},
}

// EncodingVectorByName resolves a vector. Unknown names are refused.
func EncodingVectorByName(name string) (EncodingVector, bool) {
	for _, vector := range EncodingVectors {
		if vector.Name == name {
			return vector, true
		}
	}
	return EncodingVector{}, false
}

// AdmissionVector is one planted candidate and the door's verdict. The
// admitted row is what stops the suite from being satisfied by a door that
// refuses everything.
type AdmissionVector struct {
	Name     string
	Admitted bool
	Reason   string
	Encoded  []uint64
}

// AdmissionVectors is the admission group in the kernel gate's control order.
var AdmissionVectors = []AdmissionVector{
	{Name: "clockFold", Reason: "clock-read"},
	{Name: "absenceTrigger", Reason: "absence-trigger"},
	{Name: "unfencedDecide", Reason: "unfenced-decide"},
	{Name: "lastWriterJoin", Reason: "last-writer-wins"},
	{Name: "trustingRead", Reason: "unverified-read"},
	{Name: "crossRegisterDecide", Reason: "cross-sort-identifier"},
	{Name: "mintedDeclare", Reason: "minted-identifier"},
	{Name: "latestRead", Reason: "ambient-query-input"},
	{Name: "forwardDeclare", Reason: "forward-reference"},
	{Name: "secretEmit", Reason: "secret-carrier"},
	{Name: "absenceClaimTrigger", Reason: "absence-claim"},
	{Name: "pastMutation", Reason: "past-mutation"},
	{Name: "offWritDeclare", Reason: "off-writ-referent"},
	{Name: "functionDeclare", Reason: "closure-introspection"},
	{Name: "anchoredResolve", Reason: "anchored-resolve"},
	{Name: "holeyEmit", Reason: "unfilled-hole"},
	{Name: "lawfulDeclare", Admitted: true, Encoded: []uint64{0, 0, 7000051000172, 4}},
}
