/**
 * Plane: internal — private adapters, housed flat.
 * Seam: truth — the vocabulary every sentence speaks.
 *
 * @module
 */

/**
 * The wire vocabulary, passed through from its normative home.
 *
 * **This module is emitted, not written.** Its rows are the substrate daemon's
 * own transcription tables rendered canonically and carried across the language
 * boundary unchanged: same rows, same order, same spelling. It reads no vendor
 * source of its own, because a second reading would be a second transcription,
 * and two transcriptions sharing a mistake agree perfectly. The parity wall
 * compares the two renderings byte for byte and re-derives every row's
 * provenance digest from the pinned vendor sources as installed, so what the
 * two languages agree on is anchored outside both of them.
 *
 * Hand edits do not survive: the next emission overwrites them, and until then
 * the wall refuses a file whose bytes differ from a fresh emission.
 *
 * **What a row carries.** Its wire word as the pinned vendor states it; the
 * shape of what the word carries; the provenance pin — vendor package, version,
 * and the digest of the exact source region transcribed; the estate's
 * classification of the row under the three wire shapes; and, on every row
 * classified as chatter, the promotion note saying what such a message may
 * accelerate and what it may never decide.
 *
 * **Rows the estate never reaches are still rows.** A word the pinned vendor
 * declares and this posture never speaks is carried and marked
 * declared-but-unused. Omission is how a table starts lying.
 *
 * Staged debt, stated rather than absorbed: this vocabulary is hand-carried
 * transcription owing the corpus's substrate-vocabulary emitter group, which
 * the emitter does not yet mint. It is transcription with provenance until that
 * group exists, never a twin of one.
 */

/** Which way a wire word travels. */
export type WireDirection = "client-to-server" | "server-to-client" | "either"

/** The estate's classification of a row under the three wire shapes. */
export type WireShape = "journal-fact" | "commitment-register" | "ephemeral-chatter"

/** Whether the estate speaks or hears a row at its current posture. */
export type WireUse = "spoken" | "declared-but-unused"

/** One row's provenance: the pinned package, its version, and the region digest. */
export interface WirePin {
  readonly package: string
  readonly version: string
  readonly digest: string
}

/** One transcribed payload field of one status event. */
export interface WireStatusField {
  readonly name: string
  readonly sort: string
  readonly optional: boolean
}

/** Every word the core protocol carries, in the pinned sources' own order. */
export const WIRE_PROTOCOL_VERBS = [
  {
    declaration: "server.InfoProto",
    direction: "server-to-client",
    pin: {
      digest: "322a01803c08303fb9907a5e19daf56ab37754e45773eb16c5546dca3a0796ae",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "This line is one of the three groups the substrate session folds from: it accelerates the mint by supplying its group, and it decides nothing, because the session's name is the digest of the folded value and a line that never arrived leaves no session rather than a session wearing defaults.",
    shape: "INFO <json> — the substrate's own declaration of itself, shaped by server.Info",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "INFO",
  },
  {
    declaration: "nats.connectProto",
    direction: "client-to-server",
    pin: {
      digest: "0f3d8264278677d4b8db971adbe61c70af00f90ae020eebf0fd7cc4641e38888",
      package: "github.com/nats-io/nats.go",
      version: "v1.53.1",
    },
    promotion: "This line is one of the three groups the substrate session folds from: it accelerates the mint by supplying its group, and it decides nothing, because the session's name is the digest of the folded value and a line that never arrived leaves no session rather than a session wearing defaults.",
    shape: "CONNECT <json> — the connecting process's declared options, shaped by server.ClientOpts",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "CONNECT",
  },
  {
    declaration: "nats._PUB_P_",
    direction: "client-to-server",
    pin: {
      digest: "005b60259aeffe03c82d6bef9f3e82b1a26bf18dae9cad177674c18eaaead873",
      package: "github.com/nats-io/nats.go",
      version: "v1.53.1",
    },
    promotion: "The line carries a value onto a subject. It may accelerate a reader already folding that lane, and it decides nothing: what a lane means is the fold over the values it carries, and a value that must be exactly-once meaningful is promoted by its own digest before any line carries it.",
    shape: "PUB <subject> [reply-to] <#bytes>\\r\\n<payload>",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "PUB",
  },
  {
    declaration: "nats._HPUB_P_",
    direction: "client-to-server",
    pin: {
      digest: "0ec75a273851b40d8792174965b3809462f398a5e4a2233dd32e2749c1c36ce0",
      package: "github.com/nats-io/nats.go",
      version: "v1.53.1",
    },
    promotion: "The line carries a value onto a subject. It may accelerate a reader already folding that lane, and it decides nothing: what a lane means is the fold over the values it carries, and a value that must be exactly-once meaningful is promoted by its own digest before any line carries it.",
    shape: "HPUB <subject> [reply-to] <#header-bytes> <#total-bytes>\\r\\n<headers><payload>",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "HPUB",
  },
  {
    declaration: "nats.subProto",
    direction: "client-to-server",
    pin: {
      digest: "8c75898a06828197d362e9575bd2def4274ecbbbc6aae918678a340ca6469242",
      package: "github.com/nats-io/nats.go",
      version: "v1.53.1",
    },
    promotion: "Interest is carriage. It decides which messages this connection is offered and never what any of them mean: a fold's value is a function of delivered support and query alone, so interest changes what arrives and never what it says.",
    shape: "SUB <subject> [queue-group] <sid>",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "SUB",
  },
  {
    declaration: "nats.unsubProto",
    direction: "client-to-server",
    pin: {
      digest: "0bf1ee5db7a8c8a5fc0ed8f35a83a89de83d1f118705c82204f341334e6bde47",
      package: "github.com/nats-io/nats.go",
      version: "v1.53.1",
    },
    promotion: "Interest is carriage. It decides which messages this connection is offered and never what any of them mean: a fold's value is a function of delivered support and query alone, so interest changes what arrives and never what it says.",
    shape: "UNSUB <sid> [max-msgs]",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "UNSUB",
  },
  {
    declaration: "server.msgHeadProto",
    direction: "server-to-client",
    pin: {
      digest: "fbeebe15032f3d90aa5c56438874ab584e068b428c072431d6663eb1b1a155ae",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "Delivery accelerates a reader toward a position it could also have reached by reading the lane. It decides nothing: a fold at an anchor is the same value whether the message was delivered once, redelivered, or never seen at all.",
    shape: "MSG <subject> <sid> [reply-to] <#bytes>\\r\\n<payload>",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "MSG",
  },
  {
    declaration: "server.msgHeadProto (header arm)",
    direction: "server-to-client",
    pin: {
      digest: "fbeebe15032f3d90aa5c56438874ab584e068b428c072431d6663eb1b1a155ae",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "Delivery accelerates a reader toward a position it could also have reached by reading the lane. It decides nothing: a fold at an anchor is the same value whether the message was delivered once, redelivered, or never seen at all.",
    shape: "HMSG <subject> <sid> [reply-to] <#header-bytes> <#total-bytes>\\r\\n<headers><payload>",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "HMSG",
  },
  {
    declaration: "server.pingProto",
    direction: "either",
    pin: {
      digest: "f55da92e2a438d50fb17c86ae9b58a14dd4050e564d315b440efb6e632f17992",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The liveness exchange may accelerate a client's own staleness reading. It decides nothing, because \"the substrate is alive now\" is unsayable: aliveness is productive-through-a-position, a reader's fold over heartbeat and readiness facts.",
    shape: "PING — no argument",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "PING",
  },
  {
    declaration: "server.pongProto",
    direction: "either",
    pin: {
      digest: "f0d6e9370900d694dd75bbd0b7b75dbb2c5d0f14a8eafb77a99a88135692ac56",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The liveness exchange may accelerate a client's own staleness reading. It decides nothing, because \"the substrate is alive now\" is unsayable: aliveness is productive-through-a-position, a reader's fold over heartbeat and readiness facts.",
    shape: "PONG — no argument",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "PONG",
  },
  {
    declaration: "server.okProto",
    direction: "server-to-client",
    pin: {
      digest: "62107d399cc7f59bc58b78ebec5dd39228bdf97575335f401aa13512cfd85376",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A protocol acknowledgement accelerates nothing the estate reads and decides nothing. The estate's acknowledgement of a published value is the position the lane assigned it.",
    shape: "+OK — no argument; sent only under the verbose option",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
    word: "+OK",
  },
  {
    declaration: "server.errProto",
    direction: "server-to-client",
    pin: {
      digest: "d197c022274006f895b87150b552b81f0c1cd1878f56b1cec9058fc540c03ee7",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A protocol error is the substrate's own account of a refusal. It may accelerate a client toward its own teardown and it decides nothing, because a refusal that means anything here is typed at the one door with reason, law, and repair.",
    shape: "-ERR '<message>'",
    use: "spoken",
    wire: "ephemeral-chatter",
    word: "-ERR",
  },
] as const

/** The same rows, reached by the vendor's own identifier rather than by their wire word. */
export const WIRE_VERB_BY_DECLARATION = {
  "server.InfoProto": WIRE_PROTOCOL_VERBS[0],
  "nats.connectProto": WIRE_PROTOCOL_VERBS[1],
  "nats._PUB_P_": WIRE_PROTOCOL_VERBS[2],
  "nats._HPUB_P_": WIRE_PROTOCOL_VERBS[3],
  "nats.subProto": WIRE_PROTOCOL_VERBS[4],
  "nats.unsubProto": WIRE_PROTOCOL_VERBS[5],
  "server.msgHeadProto": WIRE_PROTOCOL_VERBS[6],
  "server.msgHeadProto (header arm)": WIRE_PROTOCOL_VERBS[7],
  "server.pingProto": WIRE_PROTOCOL_VERBS[8],
  "server.pongProto": WIRE_PROTOCOL_VERBS[9],
  "server.okProto": WIRE_PROTOCOL_VERBS[10],
  "server.errProto": WIRE_PROTOCOL_VERBS[11],
} as const

/** The JetStream API and key-value subject surface, transcribed whole. */
export const WIRE_API_SUBJECTS = [
  {
    declaration: "server.jsAllAPI",
    pin: {
      digest: "b7bf809c65de2a03826118d604433b96dadb605499c7cba0522e48fafbe850ab",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$JS.API.>",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiPrefix",
    pin: {
      digest: "23602dd55931ad869ebe29a2d7931ab03cf71fd2cc9740d4c4cc3315a695436f",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$JS.API",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiAccountInfo",
    pin: {
      digest: "cfc767a916980374ae94bb0f161714ba6f570b0565630e3463d1f1dd50771dcb",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.INFO",
    template: "",
    templateDeclaration: "",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamCreate",
    pin: {
      digest: "def99aeca2cb50088617777f6e9202a1334006f67c35aadbacc386fe2ec9e021",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.CREATE.*",
    template: "$JS.API.STREAM.CREATE.%s",
    templateDeclaration: "server.JSApiStreamCreateT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamUpdate",
    pin: {
      digest: "b058ba709b89df48cf52c0abf18d022f0e7559f70453f57500e5175bba51e0a2",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.UPDATE.*",
    template: "$JS.API.STREAM.UPDATE.%s",
    templateDeclaration: "server.JSApiStreamUpdateT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreams",
    pin: {
      digest: "db669e8767f7bb02401a820056533f5d60ddc9395e42942ef7a662986c1e4969",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.STREAM.NAMES",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamList",
    pin: {
      digest: "ac52aa79d4d03d65980e1b81447a61602af49d429b983bebafac9e8eaf452964",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.STREAM.LIST",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamInfo",
    pin: {
      digest: "b21f94d19f793ad9491234f69fb67e19405b52d94a133ba3870b6955d4f164b6",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.STREAM.INFO.*",
    template: "$JS.API.STREAM.INFO.%s",
    templateDeclaration: "server.JSApiStreamInfoT",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamDelete",
    pin: {
      digest: "8439c147f12ae617f67a31d2bdefda6c7b95e9e4ea1ff7edc82b9b2b14678060",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.DELETE.*",
    template: "$JS.API.STREAM.DELETE.%s",
    templateDeclaration: "server.JSApiStreamDeleteT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamPurge",
    pin: {
      digest: "0eacfef4239aa63dbbf5d554892a0564bbba1333b561747170a4c13357881f61",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.PURGE.*",
    template: "$JS.API.STREAM.PURGE.%s",
    templateDeclaration: "server.JSApiStreamPurgeT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamSnapshot",
    pin: {
      digest: "8e48bc4724c3c79387d8ebcf2860b1fe0c41bf5ed0e9eec382babaa7fe12905d",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.SNAPSHOT.*",
    template: "$JS.API.STREAM.SNAPSHOT.%s",
    templateDeclaration: "server.JSApiStreamSnapshotT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamRestore",
    pin: {
      digest: "b83c3222785ea17bfacbf58282f3a7da5388b755201a8e3e98c41f0ac9420a95",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.RESTORE.*",
    template: "$JS.API.STREAM.RESTORE.%s",
    templateDeclaration: "server.JSApiStreamRestoreT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiMsgDelete",
    pin: {
      digest: "7d9dc3d0033dc7c99d3d814345aa61dd7eedfed40a557c688721dec7ad57a6ab",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.STREAM.MSG.DELETE.*",
    template: "$JS.API.STREAM.MSG.DELETE.%s",
    templateDeclaration: "server.JSApiMsgDeleteT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiMsgGet",
    pin: {
      digest: "f752677a714279fd30be1312a9706a2717c4748bb7558e8fad310330c39daeb6",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A direct read of one message by its coordinates. It may accelerate a resolve and it decides nothing, because a resolve is a read of bytes a digest already names and a digest read is never stale.",
    subject: "$JS.API.STREAM.MSG.GET.*",
    template: "$JS.API.STREAM.MSG.GET.%s",
    templateDeclaration: "server.JSApiMsgGetT",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSDirectMsgGet",
    pin: {
      digest: "d655d3b0f3c5b805fd4ff3a3d457f1d8807984f619bf7abaa1d85bdd54e3f3c4",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A direct read of one message by its coordinates. It may accelerate a resolve and it decides nothing, because a resolve is a read of bytes a digest already names and a digest read is never stale.",
    subject: "$JS.API.DIRECT.GET.*",
    template: "$JS.API.DIRECT.GET.%s",
    templateDeclaration: "server.JSDirectMsgGetT",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSDirectGetLastBySubject",
    pin: {
      digest: "9feb20d52a4a7d9629244b7361461c8bd2f82642d5e1bf7a7f5926f72558512a",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A direct read of one message by its coordinates. It may accelerate a resolve and it decides nothing, because a resolve is a read of bytes a digest already names and a digest read is never stale.",
    subject: "$JS.API.DIRECT.GET.*.>",
    template: "$JS.API.DIRECT.GET.%s.%s",
    templateDeclaration: "server.JSDirectGetLastBySubjectT",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.jsDirectGetPre",
    pin: {
      digest: "5abfb3468b6c5a00f4f468f4376a10556a92969138b92398ddbf0506b80d3412",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$JS.API.DIRECT.GET",
    template: "",
    templateDeclaration: "",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerCreate",
    pin: {
      digest: "859c7ac3e190674287c8323df0910467c15fcfea3f467ac4a4e18f751b8e5d1f",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.CREATE.*",
    template: "$JS.API.CONSUMER.CREATE.%s",
    templateDeclaration: "server.JSApiConsumerCreateT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerCreateEx",
    pin: {
      digest: "64e5d127a0889d3fd0b7541326fa254546b5129d0862b664590608ee16a75a07",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.CREATE.*.>",
    template: "$JS.API.CONSUMER.CREATE.%s.%s.%s",
    templateDeclaration: "server.JSApiConsumerCreateExT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiDurableCreate",
    pin: {
      digest: "d70a9b3c1f711793f4120028c7f8910f321316b59a82cc052a9c80e00feb8e8e",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.DURABLE.CREATE.*.*",
    template: "$JS.API.CONSUMER.DURABLE.CREATE.%s.%s",
    templateDeclaration: "server.JSApiDurableCreateT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumers",
    pin: {
      digest: "6e2a6a375c1e18dde56af6a4b31bc5f9210864d633f2e831ff5c4b6156026069",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.CONSUMER.NAMES.*",
    template: "$JS.API.CONSUMER.NAMES.%s",
    templateDeclaration: "server.JSApiConsumersT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerList",
    pin: {
      digest: "4f228e6e1bed715dd27e31d8fda22591c195ebd7a46051fd11dd25521b210adf",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.CONSUMER.LIST.*",
    template: "$JS.API.CONSUMER.LIST.%s",
    templateDeclaration: "server.JSApiConsumerListT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerInfo",
    pin: {
      digest: "eaa999a0fe6dac3a633f6f06adc4f09ff37c9805be554df2a0c94e3b5ca3113b",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "$JS.API.CONSUMER.INFO.*.*",
    template: "$JS.API.CONSUMER.INFO.%s.%s",
    templateDeclaration: "server.JSApiConsumerInfoT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerDelete",
    pin: {
      digest: "9369d8e986669646e2b96830abdaf53e44cc268fed8ef4315db7e52e578a8906",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.DELETE.*.*",
    template: "$JS.API.CONSUMER.DELETE.%s.%s",
    templateDeclaration: "server.JSApiConsumerDeleteT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerPause",
    pin: {
      digest: "970c6c326b57a23ef693f383dd7a79f1af84f4d768196927c0a1e743a8a0e3a4",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.PAUSE.*.*",
    template: "$JS.API.CONSUMER.PAUSE.%s.%s",
    templateDeclaration: "server.JSApiConsumerPauseT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiRequestNextT",
    pin: {
      digest: "74317dccd691027f0e8c874b0143d0421b8b78d527e287c9fd0acef520f3e2b8",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A read of the substrate's own account of itself. It may accelerate a reader toward a position and it decides nothing: presence, staleness, and history are folds over lanes, never answers a broker gives.",
    subject: "",
    template: "$JS.API.CONSUMER.MSG.NEXT.%s.%s",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerResetT",
    pin: {
      digest: "ab15005bd371f3d2a2721fe5483044932d6a2349a172d4f2aaa32b828a116828",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "",
    template: "$JS.API.CONSUMER.RESET.%s.%s",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerUnpin",
    pin: {
      digest: "f2b63e482a5872a7d394c1bfa1841af0639e15a92409398a2f841fc5bd480904",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request-reply against the substrate's own administration. It may accelerate a declared shape into existence and it decides nothing: what a stream or consumer must be is the shape the estate declared, and the reply is evidence that the substrate now matches it.",
    subject: "$JS.API.CONSUMER.UNPIN.*.*",
    template: "$JS.API.CONSUMER.UNPIN.%s.%s",
    templateDeclaration: "server.JSApiConsumerUnpinT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.jsRequestNextPre",
    pin: {
      digest: "50bea51aab44ec7632614310511aa4c623c5015e4ec5d1980e7a7fe9085e9b75",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$JS.API.CONSUMER.MSG.NEXT.",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamRemovePeer",
    pin: {
      digest: "39ce8b229ee3873423c7597e09abdaa9bf8030c1dee321a689ea45d5733dafba",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.STREAM.PEER.REMOVE.*",
    template: "$JS.API.STREAM.PEER.REMOVE.%s",
    templateDeclaration: "server.JSApiStreamRemovePeerT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiStreamLeaderStepDown",
    pin: {
      digest: "e56165ab56e21a7df0f079d1b10ab6d75f54084a2f8a6e2673097479ab67791d",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.STREAM.LEADER.STEPDOWN.*",
    template: "$JS.API.STREAM.LEADER.STEPDOWN.%s",
    templateDeclaration: "server.JSApiStreamLeaderStepDownT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiConsumerLeaderStepDown",
    pin: {
      digest: "760a48ca8fefd2122efc3af0e005e13e788ea087b89e9e457f95617e7ff3f7e6",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.CONSUMER.LEADER.STEPDOWN.*.*",
    template: "$JS.API.CONSUMER.LEADER.STEPDOWN.%s.%s",
    templateDeclaration: "server.JSApiConsumerLeaderStepDownT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiLeaderStepDown",
    pin: {
      digest: "6a6a49273d8e272178fbdad98f9f22b74ffd4ac95f796021e25b3167e58d4d2c",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.META.LEADER.STEPDOWN",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiRemoveServer",
    pin: {
      digest: "50528fd7c972cfd637d2a3d7879b93e30dc407bb15fb7747ef92cb7b13b7c93a",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.SERVER.REMOVE",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiAccountPurge",
    pin: {
      digest: "a53dee2cf23ddbf7683e12b31ff9ef1628bd4a07483044a6c73b778eeb5c2023",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.ACCOUNT.PURGE.*",
    template: "$JS.API.ACCOUNT.PURGE.%s",
    templateDeclaration: "server.JSApiAccountPurgeT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiServerStreamMove",
    pin: {
      digest: "74011734c002ae86d06f136b93de043561fbc24432b224256cbc0aeb90ab1069",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.ACCOUNT.STREAM.MOVE.*.*",
    template: "$JS.API.ACCOUNT.STREAM.MOVE.%s.%s",
    templateDeclaration: "server.JSApiServerStreamMoveT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.JSApiServerStreamCancelMove",
    pin: {
      digest: "e52c9f09fafe3d09f938459dff3f9fcf32601353defbc9bad371fdf084fbdf7a",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A clustered-substrate administration request. It may accelerate a placement decision inside the substrate and it decides nothing here: this estate's single-server posture reaches no such request, and the acts that need a winner are landed at the estate's own fenced registers.",
    subject: "$JS.API.ACCOUNT.STREAM.CANCEL_MOVE.*.*",
    template: "$JS.API.ACCOUNT.STREAM.CANCEL_MOVE.%s.%s",
    templateDeclaration: "server.JSApiServerStreamCancelMoveT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.jsAPIAccountPre",
    pin: {
      digest: "e25181f00918c5b1283fbe23d76c7626b3c6078d40be67da7ea6257074b5378d",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$JS.API.ACCOUNT.",
    template: "",
    templateDeclaration: "",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "kv.kvSubjectPrefix",
    pin: {
      digest: "3678b59cb0e314e205dd916f6e5c7e593b6b3f7c4c33821c40a93b6a34c95065",
      package: "@nats-io/kv",
      version: "3.4.0",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "$KV",
    template: "",
    templateDeclaration: "",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "kv.kvPrefix",
    pin: {
      digest: "eb08e31fc824c5cf1ed87ecade930fec0469ccfe83ca202ca0d5762f26320fd6",
      package: "@nats-io/kv",
      version: "3.4.0",
    },
    promotion: "A subject-family prefix rather than a request subject: it names where a family lives so a grant or a deny can address the family whole. It accelerates nothing on its own and decides nothing, because authority is what a writ declares and a prefix is only how that declaration is spelled.",
    subject: "KV_",
    template: "",
    templateDeclaration: "",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
] as const

/** The same rows, reached by the vendor's own identifier rather than by their wire word. */
export const WIRE_API_SUBJECT_BY_DECLARATION = {
  "server.jsAllAPI": WIRE_API_SUBJECTS[0],
  "server.JSApiPrefix": WIRE_API_SUBJECTS[1],
  "server.JSApiAccountInfo": WIRE_API_SUBJECTS[2],
  "server.JSApiStreamCreate": WIRE_API_SUBJECTS[3],
  "server.JSApiStreamUpdate": WIRE_API_SUBJECTS[4],
  "server.JSApiStreams": WIRE_API_SUBJECTS[5],
  "server.JSApiStreamList": WIRE_API_SUBJECTS[6],
  "server.JSApiStreamInfo": WIRE_API_SUBJECTS[7],
  "server.JSApiStreamDelete": WIRE_API_SUBJECTS[8],
  "server.JSApiStreamPurge": WIRE_API_SUBJECTS[9],
  "server.JSApiStreamSnapshot": WIRE_API_SUBJECTS[10],
  "server.JSApiStreamRestore": WIRE_API_SUBJECTS[11],
  "server.JSApiMsgDelete": WIRE_API_SUBJECTS[12],
  "server.JSApiMsgGet": WIRE_API_SUBJECTS[13],
  "server.JSDirectMsgGet": WIRE_API_SUBJECTS[14],
  "server.JSDirectGetLastBySubject": WIRE_API_SUBJECTS[15],
  "server.jsDirectGetPre": WIRE_API_SUBJECTS[16],
  "server.JSApiConsumerCreate": WIRE_API_SUBJECTS[17],
  "server.JSApiConsumerCreateEx": WIRE_API_SUBJECTS[18],
  "server.JSApiDurableCreate": WIRE_API_SUBJECTS[19],
  "server.JSApiConsumers": WIRE_API_SUBJECTS[20],
  "server.JSApiConsumerList": WIRE_API_SUBJECTS[21],
  "server.JSApiConsumerInfo": WIRE_API_SUBJECTS[22],
  "server.JSApiConsumerDelete": WIRE_API_SUBJECTS[23],
  "server.JSApiConsumerPause": WIRE_API_SUBJECTS[24],
  "server.JSApiRequestNextT": WIRE_API_SUBJECTS[25],
  "server.JSApiConsumerResetT": WIRE_API_SUBJECTS[26],
  "server.JSApiConsumerUnpin": WIRE_API_SUBJECTS[27],
  "server.jsRequestNextPre": WIRE_API_SUBJECTS[28],
  "server.JSApiStreamRemovePeer": WIRE_API_SUBJECTS[29],
  "server.JSApiStreamLeaderStepDown": WIRE_API_SUBJECTS[30],
  "server.JSApiConsumerLeaderStepDown": WIRE_API_SUBJECTS[31],
  "server.JSApiLeaderStepDown": WIRE_API_SUBJECTS[32],
  "server.JSApiRemoveServer": WIRE_API_SUBJECTS[33],
  "server.JSApiAccountPurge": WIRE_API_SUBJECTS[34],
  "server.JSApiServerStreamMove": WIRE_API_SUBJECTS[35],
  "server.JSApiServerStreamCancelMove": WIRE_API_SUBJECTS[36],
  "server.jsAPIAccountPre": WIRE_API_SUBJECTS[37],
  "kv.kvSubjectPrefix": WIRE_API_SUBJECTS[38],
  "kv.kvPrefix": WIRE_API_SUBJECTS[39],
} as const

/** The system-account event subject surface, transcribed in full. */
export const WIRE_SYSTEM_SUBJECTS = [
  {
    declaration: "server.accLookupReqSubj",
    pin: {
      digest: "d41062d2ff7531ea9981bda7b72b08741fa04db78ff2da4cbfc8e13826319c46",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.ACCOUNT.%s.CLAIMS.LOOKUP",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accPackReqSubj",
    pin: {
      digest: "a4c6eb97508fc46e431b64a23d2de8451e213e669a2ec7a99ab3b6eab9961f79",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.CLAIMS.PACK",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accListReqSubj",
    pin: {
      digest: "fa320a0251a8fd74a3ad8889c94569fdc4a331fdb747ae755a20d423bf256f00",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.CLAIMS.LIST",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accClaimsReqSubj",
    pin: {
      digest: "26413b0f98a01e76a6e2c6aaa2cb6387571f7daf53635282f795dd2573aa3ff7",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.CLAIMS.UPDATE",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accDeleteReqSubj",
    pin: {
      digest: "328800265838a7ac5b12e1f2c7d0e85bfb6cfbb4ad2ca1cc27483dfe407be8b7",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.CLAIMS.DELETE",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.connectEventSubj",
    pin: {
      digest: "6cf716e0de66037c0cb4159c0b868c1e6045d874218369b1e5f462733af36eaf",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.ACCOUNT.%s.CONNECT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.disconnectEventSubj",
    pin: {
      digest: "dd1f94097142879b763a31ca59feb9a722d4a58937302c724aa02a96a33ffdca",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.ACCOUNT.%s.DISCONNECT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accDirectReqSubj",
    pin: {
      digest: "cd34b8189c2f4e3b0782e32bf8c1fa681df7a8638acfac9dd9e2a26571670448",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.ACCOUNT.%s.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accPingReqSubj",
    pin: {
      digest: "f3c79a3d2ba663849b37d7462d53341489550186745f2dcac6371b387dd02b88",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.ACCOUNT.PING.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accUpdateEventSubjOld",
    pin: {
      digest: "d82d3053a45ce334a9f1231076ace87b2cfb78465af2ceaf1f4f57ae1bcafb79",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.ACCOUNT.%s.CLAIMS.UPDATE",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accUpdateEventSubjNew",
    pin: {
      digest: "a03d13a62e347572ab07a850414b784af0b7830a5e0349988e9bf7c3695dbaba",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "An account-claims exchange for an operator-run resolver. It may accelerate a credential's propagation and it decides nothing: credential custody is host engineering and stays outside the meaning path.",
    subject: "$SYS.REQ.ACCOUNT.%s.CLAIMS.UPDATE",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.connsRespSubj",
    pin: {
      digest: "e2cac7b3301d9141de004d18cef6a7f53b1699f6e44f96f7d059e6b70289e032",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A system-account inbox coordinate: where a reply to one of these requests is addressed. It accelerates a request-reply round trip and decides nothing, because the reply is chatter whatever coordinate carried it.",
    subject: "$SYS._INBOX_.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accConnsEventSubjNew",
    pin: {
      digest: "741196e35d054c46a5ecfbb4350ecd5bd192386dd51d0df7d4a5d71796effd77",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.ACCOUNT.%s.SERVER.CONNS",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accConnsEventSubjOld",
    pin: {
      digest: "d021b7037dbad7ef45dfe889453cead5e199ab6c40bfd0c49697c7bcddc9b5da",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.SERVER.ACCOUNT.%s.CONNS",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.lameDuckEventSubj",
    pin: {
      digest: "5c0a2820657ff66589f774773cf95bd17bfb7b65ac47deabd74a86c4a99f7c6f",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.LAMEDUCK",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.shutdownEventSubj",
    pin: {
      digest: "42498613a0d6ff38cb765909e87260e7751a7702049f9f2ed7ebbed07be676e5",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.SHUTDOWN",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.clientKickReqSubj",
    pin: {
      digest: "22460ac2d7b776f41e600ba4ece3fbf8b378a67e47c866b2aa20205fb7f6371b",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.%s.KICK",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.clientLDMReqSubj",
    pin: {
      digest: "2a6f741989e634548486c5a407a099ce9d4d57cec8b5d69767c462a9c2731bd5",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.%s.LDM",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.authErrorEventSubj",
    pin: {
      digest: "7da47b49626a7d329997595aae33079badda68e78af609d02258af6b8dbdead7",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.CLIENT.AUTH.ERR",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.authErrorAccountEventSubj",
    pin: {
      digest: "867d3c9cb4e4637d6ac5bf9465a924f49ac4887ead476df0fddf94097ecccd38",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.ACCOUNT.CLIENT.AUTH.ERR",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.serverStatsSubj",
    pin: {
      digest: "b710c12ee1960a8dc30bd8f5fc1bc5cf9ef8c18f565291b694414995baa78dd1",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.STATSZ",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.serverDirectReqSubj",
    pin: {
      digest: "355602d9ccf5c07171e17172e452c9b34cb4ac159ab6cef6a2eb650fd78ad620",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.%s.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.serverPingReqSubj",
    pin: {
      digest: "0d1e295da655ba3b369eab109ec6b3edd04033b2769a54e869f2889ed1764925",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.PING.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.serverStatsPingReqSubj",
    pin: {
      digest: "2d5c6959d021dd35865c57037ae3b0548a876bef21f588dfd5dbe993a48cfe3a",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.PING",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.serverReloadReqSubj",
    pin: {
      digest: "696ff54e13481c3283e8be246d8eded5cb46ea9d4628b20e4e42dca608ccc067",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.SERVER.%s.RELOAD",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.leafNodeConnectEventSubj",
    pin: {
      digest: "d2a6b1457ee832fedeb71f1941651f2ef266a0bf35e37cb528b1705ed5f5f898",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of an account-scoped occurrence. It may accelerate a fold that is already reading the session lane and it decides nothing: presence is a fold over established-and-not-ended facts, and a broker's view of who is connected is both late and, for reaped connections, wrong.",
    subject: "$SYS.ACCOUNT.%s.LEAFNODE.CONNECT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.remoteLatencyEventSubj",
    pin: {
      digest: "a09d36696db867148868277b2e5fdae9cdb3a799dfff6604fa7ea0b546e14510",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A debug or measurement service the substrate exports about itself. It may accelerate an investigation and it decides nothing, because a measurement is never a fact of the record unless somebody emits one citing it.",
    subject: "$SYS.LATENCY.M2.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.inboxRespSubj",
    pin: {
      digest: "39b4c0f3d3c61d540d271b30bc556e18a51dfb4d71ff292e280f58218192d757",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A system-account inbox coordinate: where a reply to one of these requests is addressed. It accelerates a request-reply round trip and decides nothing, because the reply is chatter whatever coordinate carried it.",
    subject: "$SYS._INBOX.%s.%s",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.userDirectInfoSubj",
    pin: {
      digest: "deaf3ead9230c2a72b0471ebf1b691fd68ac659d12e9b2f6f16c0e4f451becfc",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.USER.INFO",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.userDirectReqSubj",
    pin: {
      digest: "7ce28c4913fefbcb3df7ccd0f959d061d61340ff797f3ad103d3635c3a8a05e6",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.USER.%s.INFO",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accNumSubsReqSubj",
    pin: {
      digest: "dedfd87df785078f1fed7fb1a01787bcf2652b38d42937c4b5f86c7c0b30dd5b",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.ACCOUNT.NSUBS",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.accSubsSubj",
    pin: {
      digest: "401ea9551674b1f9135989558cd0403f9a80dd812876c024a75f227a59fa7034",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A debug or measurement service the substrate exports about itself. It may accelerate an investigation and it decides nothing, because a measurement is never a fact of the record unless somebody emits one citing it.",
    subject: "$SYS.DEBUG.SUBSCRIBERS",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.ocspPeerRejectEventSubj",
    pin: {
      digest: "7a84da17bf345ba55f6d0723213a380b452cd82ac52c140868e2412b777a208b",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.OCSP.PEER.CONN.REJECT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.ocspPeerChainlinkInvalidEventSubj",
    pin: {
      digest: "274ba45fe4ef9c0eec5e957a3c81c5970484b16f2418000e81c9f2753bad88bf",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.SERVER.%s.OCSP.PEER.LINK.INVALID",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.InboxPrefix",
    pin: {
      digest: "9e97fc5b966b09468600feaa5e57debd9e8ce78f862b1c61a731dcf9706efd64",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A system-account inbox coordinate: where a reply to one of these requests is addressed. It accelerates a request-reply round trip and decides nothing, because the reply is chatter whatever coordinate carried it.",
    subject: "$SYS._INBOX.",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.AuthCalloutSubject",
    pin: {
      digest: "30d930864e70778db0b313279c60310de87500ca0124c5db9010b3fc36f662c1",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A request into the substrate's system account. It may accelerate an operator act and it decides nothing here: the acts with blast radius are the operator's, outside the algebra, and nothing the estate folds is a function of a reply to one of these.",
    subject: "$SYS.REQ.USER.AUTH",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.streamAssignmentSubj",
    pin: {
      digest: "ef25ab8fe674c084a33fbf353c92f3e96f89a3b2ce8a4d7bb04278ae483e2229",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.JSC.STREAM.ASSIGNMENT.RESULT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "server.consumerAssignmentSubj",
    pin: {
      digest: "a319d3a277c86f973105991747f9b4ca15ea147164c6c94de5371c1520ef7c50",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The substrate's own account of its own lifecycle. It may accelerate a supervisor toward looking sooner and it decides nothing: what the estate knows about an incarnation is the incarnation lane, whose facts a fenced decide lands.",
    subject: "$SYS.JSC.CONSUMER.ASSIGNMENT.RESULT",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
] as const

/** The same rows, reached by the vendor's own identifier rather than by their wire word. */
export const WIRE_SYSTEM_SUBJECT_BY_DECLARATION = {
  "server.accLookupReqSubj": WIRE_SYSTEM_SUBJECTS[0],
  "server.accPackReqSubj": WIRE_SYSTEM_SUBJECTS[1],
  "server.accListReqSubj": WIRE_SYSTEM_SUBJECTS[2],
  "server.accClaimsReqSubj": WIRE_SYSTEM_SUBJECTS[3],
  "server.accDeleteReqSubj": WIRE_SYSTEM_SUBJECTS[4],
  "server.connectEventSubj": WIRE_SYSTEM_SUBJECTS[5],
  "server.disconnectEventSubj": WIRE_SYSTEM_SUBJECTS[6],
  "server.accDirectReqSubj": WIRE_SYSTEM_SUBJECTS[7],
  "server.accPingReqSubj": WIRE_SYSTEM_SUBJECTS[8],
  "server.accUpdateEventSubjOld": WIRE_SYSTEM_SUBJECTS[9],
  "server.accUpdateEventSubjNew": WIRE_SYSTEM_SUBJECTS[10],
  "server.connsRespSubj": WIRE_SYSTEM_SUBJECTS[11],
  "server.accConnsEventSubjNew": WIRE_SYSTEM_SUBJECTS[12],
  "server.accConnsEventSubjOld": WIRE_SYSTEM_SUBJECTS[13],
  "server.lameDuckEventSubj": WIRE_SYSTEM_SUBJECTS[14],
  "server.shutdownEventSubj": WIRE_SYSTEM_SUBJECTS[15],
  "server.clientKickReqSubj": WIRE_SYSTEM_SUBJECTS[16],
  "server.clientLDMReqSubj": WIRE_SYSTEM_SUBJECTS[17],
  "server.authErrorEventSubj": WIRE_SYSTEM_SUBJECTS[18],
  "server.authErrorAccountEventSubj": WIRE_SYSTEM_SUBJECTS[19],
  "server.serverStatsSubj": WIRE_SYSTEM_SUBJECTS[20],
  "server.serverDirectReqSubj": WIRE_SYSTEM_SUBJECTS[21],
  "server.serverPingReqSubj": WIRE_SYSTEM_SUBJECTS[22],
  "server.serverStatsPingReqSubj": WIRE_SYSTEM_SUBJECTS[23],
  "server.serverReloadReqSubj": WIRE_SYSTEM_SUBJECTS[24],
  "server.leafNodeConnectEventSubj": WIRE_SYSTEM_SUBJECTS[25],
  "server.remoteLatencyEventSubj": WIRE_SYSTEM_SUBJECTS[26],
  "server.inboxRespSubj": WIRE_SYSTEM_SUBJECTS[27],
  "server.userDirectInfoSubj": WIRE_SYSTEM_SUBJECTS[28],
  "server.userDirectReqSubj": WIRE_SYSTEM_SUBJECTS[29],
  "server.accNumSubsReqSubj": WIRE_SYSTEM_SUBJECTS[30],
  "server.accSubsSubj": WIRE_SYSTEM_SUBJECTS[31],
  "server.ocspPeerRejectEventSubj": WIRE_SYSTEM_SUBJECTS[32],
  "server.ocspPeerChainlinkInvalidEventSubj": WIRE_SYSTEM_SUBJECTS[33],
  "server.InboxPrefix": WIRE_SYSTEM_SUBJECTS[34],
  "server.AuthCalloutSubject": WIRE_SYSTEM_SUBJECTS[35],
  "server.streamAssignmentSubj": WIRE_SYSTEM_SUBJECTS[36],
  "server.consumerAssignmentSubj": WIRE_SYSTEM_SUBJECTS[37],
} as const

/** The client status event vocabulary, in the pinned client's declaration order. */
export const WIRE_STATUS_EVENTS = [
  {
    declaration: "DisconnectStatus",
    payload: [
      {
        name: "server",
        optional: false,
        sort: "string",
      },
    ],
    pin: {
      digest: "75f1e44cc5edcc21f1a58e620c22ee986abda0351889d714d5673410637a94aa",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "disconnect",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    declaration: "ReconnectStatus",
    payload: [
      {
        name: "server",
        optional: false,
        sort: "string",
      },
    ],
    pin: {
      digest: "365136a493aaece4d0d9705d5157d63d48881a1979eb8760386c5361cdc6b84a",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "reconnect",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    declaration: "ReconnectingStatus",
    payload: [],
    pin: {
      digest: "bfe955a397f07aeb483ee3ae83140c878fa41cb163f9d39541ab1b5821bc8031",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "reconnecting",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    declaration: "ClusterUpdateStatus",
    payload: [
      {
        name: "added",
        optional: true,
        sort: "string-list",
      },
      {
        name: "deleted",
        optional: true,
        sort: "string-list",
      },
    ],
    pin: {
      digest: "77a9257cb293876d394ce3f3f943152848f81ec0cb0a41afc3033ea5b7394cdc",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "observation",
    promotion: "A reading WITHIN a state rather than a change of state. It may accelerate a reader's own sense of how a connection is doing, and it decides nothing: promoting a reading to a state would name a state the vendor never declared, which is exactly the invention the vocabulary ruling forbids.",
    type: "update",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "LDMStatus",
    payload: [
      {
        name: "server",
        optional: false,
        sort: "string",
      },
    ],
    pin: {
      digest: "3c000fba97cbbdde95a400daf7dfa64e1ed612a4bc41daf4316e2e6634cbd3da",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "ldm",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    declaration: "ServerErrorStatus",
    payload: [
      {
        name: "error",
        optional: false,
        sort: "error-object",
      },
    ],
    pin: {
      digest: "ac13833d815743bfea192b09605855c202cede164a0eeab6254c54aa418147bd",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "observation",
    promotion: "A reading WITHIN a state rather than a change of state. It may accelerate a reader's own sense of how a connection is doing, and it decides nothing: promoting a reading to a state would name a state the vendor never declared, which is exactly the invention the vocabulary ruling forbids.",
    type: "error",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "ClientPingStatus",
    payload: [
      {
        name: "pendingPings",
        optional: false,
        sort: "number",
      },
    ],
    pin: {
      digest: "0a0506d5f2068ec5714e4722f62e89bec5fcf63c45ffaf2829e0d75965c1c73e",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "observation",
    promotion: "A reading WITHIN a state rather than a change of state. It may accelerate a reader's own sense of how a connection is doing, and it decides nothing: promoting a reading to a state would name a state the vendor never declared, which is exactly the invention the vocabulary ruling forbids.",
    type: "ping",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "StaleConnectionStatus",
    payload: [],
    pin: {
      digest: "bc39283daad086cdcf966d22020ee134f2b2e236e93f01b77d0e2dc314d55e14",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "staleConnection",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    declaration: "ForceReconnectStatus",
    payload: [],
    pin: {
      digest: "a9375134973facdaba2d9c50386045823006d88768a5957175729d614a3b59ea",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "forceReconnect",
    use: "declared-but-unused",
    wire: "journal-fact",
  },
  {
    declaration: "SlowConsumerStatus",
    payload: [
      {
        name: "sub",
        optional: false,
        sort: "subscription",
      },
      {
        name: "pending",
        optional: false,
        sort: "number",
      },
    ],
    pin: {
      digest: "3e67157be16caa5a86f011a6c34dd421571657f36d6b5b64517aac7f096f708d",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "observation",
    promotion: "A reading WITHIN a state rather than a change of state. It may accelerate a reader's own sense of how a connection is doing, and it decides nothing: promoting a reading to a state would name a state the vendor never declared, which is exactly the invention the vocabulary ruling forbids.",
    type: "slowConsumer",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    declaration: "CloseStatus",
    payload: [],
    pin: {
      digest: "8e1bae233955f533b33fa99dea8fbc53e96856569438aa5a542dd339a6a56251",
      package: "@nats-io/nats-core",
      version: "3.4.0",
    },
    placement: "transition",
    promotion: "",
    type: "close",
    use: "spoken",
    wire: "journal-fact",
  },
] as const

/** The same rows, reached by the vendor's own identifier rather than by their wire word. */
export const WIRE_STATUS_BY_DECLARATION = {
  "DisconnectStatus": WIRE_STATUS_EVENTS[0],
  "ReconnectStatus": WIRE_STATUS_EVENTS[1],
  "ReconnectingStatus": WIRE_STATUS_EVENTS[2],
  "ClusterUpdateStatus": WIRE_STATUS_EVENTS[3],
  "LDMStatus": WIRE_STATUS_EVENTS[4],
  "ServerErrorStatus": WIRE_STATUS_EVENTS[5],
  "ClientPingStatus": WIRE_STATUS_EVENTS[6],
  "StaleConnectionStatus": WIRE_STATUS_EVENTS[7],
  "ForceReconnectStatus": WIRE_STATUS_EVENTS[8],
  "SlowConsumerStatus": WIRE_STATUS_EVENTS[9],
  "CloseStatus": WIRE_STATUS_EVENTS[10],
} as const

/** The substrate's lifecycle surface, with each signature as the pinned source states it. */
export const WIRE_LIFECYCLE_ENTRIES = [
  {
    entry: "server.NewServer",
    phase: "acquire",
    pin: {
      digest: "6cf13ecdbd6363237039ea7a947eb99d5cc86ba803fcb7781ec2c53739d6c176",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "Construction is carriage and accelerates nothing. It decides nothing: the meaning of the acquire phase is the declared server-options value, whose digest the incarnation cites, and a server constructed from a value nobody declared is what the admission door refuses before any listener could bind.",
    signature: "func NewServer(opts *Options) (*Server, error)",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    entry: "server.Server.Start",
    phase: "start",
    pin: {
      digest: "0bf0339e5b2ad5217c9af92150ca37748e908c962a05dd4ee577b0e1412311e9",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "",
    signature: "func (s *Server) Start()",
    use: "spoken",
    wire: "commitment-register",
  },
  {
    entry: "server.Server.ReadyForConnections",
    phase: "ready",
    pin: {
      digest: "7d9934528ca0336e7b814ec47c64dc4fca22fc5f17c5980a5d312883af66401f",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "",
    signature: "func (s *Server) ReadyForConnections(dur time.Duration) bool",
    use: "spoken",
    wire: "journal-fact",
  },
  {
    entry: "server.Server.Running",
    phase: "serve",
    pin: {
      digest: "d27202317ec934a227186e0b7a8323282a6f4f113a31892d4d8b1aeb809b4403",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A local view's answer to \"is it up\". It may accelerate a supervisor toward looking and it decides nothing, because aliveness is unsayable as a present-tense fact and prolonged silence is refused at the supervisor's fence, never by a boolean.",
    signature: "func (s *Server) Running() bool",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    entry: "server.Server.LameDuckShutdown",
    phase: "drain",
    pin: {
      digest: "52da736daa6dd07d25db2d783156ea92e24a5e371067e158e0d10b5928125155",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "",
    signature: "func (s *Server) LameDuckShutdown()",
    use: "spoken",
    wire: "commitment-register",
  },
  {
    entry: "server.Server.Shutdown",
    phase: "stop",
    pin: {
      digest: "1f74bc25d36cbb58cae2d56ef4ba82aa701e859ac9d7fb4eb60f5ab9bdb1185c",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "",
    signature: "func (s *Server) Shutdown()",
    use: "spoken",
    wire: "commitment-register",
  },
  {
    entry: "server.Server.WaitForShutdown",
    phase: "stop",
    pin: {
      digest: "5af6e9545b980eecc00f3e3bf6f3bf3a88da74b69006380bf15ccf46f761982f",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A join on the process value. It is carriage ordering — a caller waiting for a teardown already decided — and it decides nothing that the disposition at the register did not already decide.",
    signature: "func (s *Server) WaitForShutdown()",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    entry: "server.Server.ClientURL",
    phase: "serve",
    pin: {
      digest: "12cd89dec0061941aa231446bff8864a9d220ff6a04603f4b752ee1ecda54248",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "A coordinate the substrate hands its own clients. It accelerates connecting and decides nothing: a session fact pins the digest of the connect options it was established under, never the address it dialled.",
    signature: "func (s *Server) ClientURL() string",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    entry: "server.Server.InProcessConn",
    phase: "serve",
    pin: {
      digest: "2fcb19e50b3ef92347c3ac1d7a77344d3bd60963edb41c8753eda92cf50ecac9",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "The daemon's own client-zero transport. It is carriage: the connection it opens mints a substrate-session fact like any other, and which transport carried the establishment is not part of what the fact means.",
    signature: "func (s *Server) InProcessConn() (net.Conn, error)",
    use: "spoken",
    wire: "ephemeral-chatter",
  },
  {
    entry: "server.Server.EnableJetStream",
    phase: "acquire",
    pin: {
      digest: "7a31628a4d4b3b085b340d317bbc0c73de4a6571d5c9d1f5f585f19682d37620",
      package: "github.com/nats-io/nats-server/v2",
      version: "v2.14.4",
    },
    promotion: "Enabling the resource plane is carriage under an incarnation the register has already landed. It decides nothing on its own: the one running server over a store directory is decided at the incarnation register, and that the resource plane is on is what the declared options value says.",
    signature: "func (s *Server) EnableJetStream(config *JetStreamConfig) error",
    use: "declared-but-unused",
    wire: "ephemeral-chatter",
  },
] as const

/** The same rows, reached by the vendor's own identifier rather than by their wire word. */
export const WIRE_LIFECYCLE_BY_ENTRY = {
  "server.NewServer": WIRE_LIFECYCLE_ENTRIES[0],
  "server.Server.Start": WIRE_LIFECYCLE_ENTRIES[1],
  "server.Server.ReadyForConnections": WIRE_LIFECYCLE_ENTRIES[2],
  "server.Server.Running": WIRE_LIFECYCLE_ENTRIES[3],
  "server.Server.LameDuckShutdown": WIRE_LIFECYCLE_ENTRIES[4],
  "server.Server.Shutdown": WIRE_LIFECYCLE_ENTRIES[5],
  "server.Server.WaitForShutdown": WIRE_LIFECYCLE_ENTRIES[6],
  "server.Server.ClientURL": WIRE_LIFECYCLE_ENTRIES[7],
  "server.Server.InProcessConn": WIRE_LIFECYCLE_ENTRIES[8],
  "server.Server.EnableJetStream": WIRE_LIFECYCLE_ENTRIES[9],
} as const

/**
 * The whole vocabulary as one value, composed from the five tables above.
 *
 * The composition is what the parity wall renders and compares: a second
 * statement of the rows here would be a twin of the five tables rather than
 * a rendering of them.
 */
export const WIRE_VOCABULARY = {
  v: 0,
  kind: "substrate-wire-vocabulary",
  groups: [
    { group: "protocol-verbs", rows: WIRE_PROTOCOL_VERBS },
    { group: "api-subjects", rows: WIRE_API_SUBJECTS },
    { group: "system-subjects", rows: WIRE_SYSTEM_SUBJECTS },
    { group: "status-events", rows: WIRE_STATUS_EVENTS },
    { group: "lifecycle-entries", rows: WIRE_LIFECYCLE_ENTRIES },
  ],
} as const
