// wirefix generates the golden byte fixtures in proto/wire/fixtures —
// ONCE, from the Go side (the fixture discipline: fixtures are
// evidence, generated by one side and frozen; both sides wall against
// them independently). It refuses to overwrite existing fixtures
// unless -force is given with a stated reason committed alongside.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/nats-io/nats.go"

	"foldlab/canonical"
	"foldlab/proto/protod"
)

type typeVector struct {
	Name      string `json:"name"`
	Structure any    `json:"structure"`
	Canonical string `json:"canonical"`
	Digest    string `json:"digest"`
}

type chainVector struct {
	Name         string   `json:"name"`
	Payloads     []string `json:"payloads"`
	EntryDigests []string `json:"entryDigests"`
	Head         string   `json:"head"`
}

type frameVector struct {
	Name      string `json:"name"`
	Frame     any    `json:"frame"`
	Canonical string `json:"canonical"`
}

type conciergeVector struct {
	Name             string `json:"name"`
	Subject          string `json:"subject"`
	Request          any    `json:"request"`
	RequestCanonical string `json:"requestCanonical"`
	Reply            any    `json:"reply"`
	ReplyCanonical   string `json:"replyCanonical"`
}

func mustCanonical(value any) string {
	raw, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	bytes, err := canonical.Canonicalize(raw)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

func vector(name string, structure any) typeVector {
	c := mustCanonical(structure)
	return typeVector{
		Name:      name,
		Structure: structure,
		Canonical: c,
		Digest:    canonical.DigestHex([]byte(c)),
	}
}

func m(pairs ...any) map[string]any {
	out := map[string]any{}
	for i := 0; i < len(pairs); i += 2 {
		out[pairs[i].(string)] = pairs[i+1]
	}
	return out
}

func union(members ...any) map[string]any {
	sort.Slice(members, func(i, j int) bool {
		return mustCanonical(members[i]) < mustCanonical(members[j])
	})
	return m("k", "union", "of", members)
}

func buildTypes() []typeVector {
	str := m("k", "string")
	sensor := m(
		"k", "struct",
		"fields", m(
			"id", m("k", "brand", "name", "SensorId", "of", str),
			"celsius", m("k", "float"),
			"count", m("k", "int"),
			"mode", union(
				m("k", "literal", "value", "on"),
				m("k", "literal", "value", "off"),
			),
			"note", str,
		),
		"optional", []any{"note"},
	)
	sensorDigest := canonical.DigestHex([]byte(mustCanonical(sensor)))

	return []typeVector{
		vector("leaf-string", str),
		vector("leaf-bool", m("k", "bool")),
		vector("leaf-int", m("k", "int")),
		vector("leaf-float", m("k", "float")),
		vector("leaf-null", m("k", "null")),
		vector("literal-string", m("k", "literal", "value", "on")),
		vector("literal-number-normalizes", m("k", "literal", "value", 10.0)),
		vector("literal-bool", m("k", "literal", "value", true)),
		vector("literal-null", m("k", "literal", "value", nil)),
		vector("list-of-string", m("k", "list", "of", str)),
		// Field names sort by UTF-16 code units: "Z" < "a" < "é"
		vector("struct-utf16-key-order", m(
			"k", "struct",
			"fields", m("a", str, "Z", m("k", "int"), "é", m("k", "bool")),
			"optional", []any{"é"},
		)),
		vector("union", union(str, m("k", "null"))),
		vector("brand", m("k", "brand", "name", "UserId", "of", str)),
		vector("check-min-length", m(
			"k", "check", "base", str,
			"check", m("name", "minLength", "args", m("min", 1)),
		)),
		vector("opaque", m("k", "opaque")),
		vector("sensor-reading", sensor),
		vector("ref-with-check", m(
			"k", "check",
			"base", m("k", "ref", "digest", sensorDigest),
			"check", m("name", "minLength", "args", m("min", 1)),
		)),
		vector("string-escapes", m(
			"k", "struct",
			"fields", m("naïve \"quoted\"\n\ttab", str),
			"optional", []any{},
		)),
	}
}

func buildChains(types []typeVector) []chainVector {
	sensor := types[len(types)-3] // sensor-reading
	record := m(
		"digest", sensor.Digest,
		"scheme", "bytes-sha256-v1",
		"structure", sensor.Structure,
		"submitter", "wirefix",
	)
	framePayload := mustCanonical(m(
		"type", sensor.Digest,
		"payload", m("id", "s-1", "celsius", 21.5, "count", 3, "mode", "on"),
	))

	simple := []string{"a", "b", "c"}
	simpleDigests, simpleHead := canonical.BuildChain(simple)

	catalogPayloads := []string{mustCanonical(record), framePayload}
	catalogDigests, catalogHead := canonical.BuildChain(catalogPayloads)

	return []chainVector{
		{Name: "simple", Payloads: simple, EntryDigests: simpleDigests, Head: simpleHead},
		{Name: "catalog-then-frame", Payloads: catalogPayloads, EntryDigests: catalogDigests, Head: catalogHead},
	}
}

func buildFrames(types []typeVector) []frameVector {
	sensor := types[len(types)-3]
	plain := m(
		"type", sensor.Digest,
		"payload", m("id", "s-1", "celsius", 21.5, "count", 3, "mode", "on"),
	)
	tricky := m(
		"type", sensor.Digest,
		"payload", m(
			"id", "s-☃", // snowman: multibyte UTF-8
			"celsius", 1.0, // JCS: serializes as "1"
			"count", 1000000, // stays plain notation
			"mode", "off",
			"note", "line\nbreak \"q\"",
		),
	)
	return []frameVector{
		{Name: "plain", Frame: plain, Canonical: mustCanonical(plain)},
		{Name: "unicode-and-number-normalization", Frame: tricky, Canonical: mustCanonical(tricky)},
	}
}

func buildConcierge() []conciergeVector {
	store, err := os.MkdirTemp("", "flb-wirefix-concierge-")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(store)

	daemon, err := protod.Acquire(context.Background(), protod.Options{StoreDir: store})
	if err != nil {
		panic(err)
	}
	defer daemon.Release()
	conn, err := nats.Connect(daemon.URL())
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	hole := m("k", "hole")
	listHole := m("k", "list", "of", hole)
	cases := []struct {
		name    string
		subject string
		request any
	}{
		{
			name:    "fill-bare-hole",
			subject: "flb.req.type.fill",
			request: m("partial", hole, "path", []any{}, "subtree", hole),
		},
		{
			name:    "fill-list-child",
			subject: "flb.req.type.fill",
			request: m("partial", listHole, "path", []any{"of"}, "subtree", m("k", "string")),
		},
		{
			name:    "unfill-list-child",
			subject: "flb.req.type.unfill",
			request: m(
				"partial", m("k", "list", "of", m("k", "string")),
				"path", []any{"of"},
			),
		},
		{
			name:    "fill-non-hole-refusal",
			subject: "flb.req.type.fill",
			request: m(
				"partial", m("k", "string"),
				"path", []any{},
				"subtree", m("k", "bool"),
			),
		},
		{
			name:    "fill-unknown-ref-refusal",
			subject: "flb.req.type.fill",
			request: m(
				"partial", hole,
				"path", []any{},
				"subtree", m("k", "ref", "digest", "9999999999999999999999999999999999999999999999999999999999999999"),
			),
		},
		{
			name:    "unfill-invalid-path-refusal",
			subject: "flb.req.type.unfill",
			request: m("partial", m("k", "string"), "path", []any{"of"}),
		},
	}

	vectors := make([]conciergeVector, 0, len(cases))
	for _, fixture := range cases {
		requestCanonical := mustCanonical(fixture.request)
		message, err := conn.Request(fixture.subject, []byte(requestCanonical), 20*time.Second)
		if err != nil {
			panic(err)
		}
		var reply any
		if err := json.Unmarshal(message.Data, &reply); err != nil {
			panic(err)
		}
		vectors = append(vectors, conciergeVector{
			Name:             fixture.name,
			Subject:          fixture.subject,
			Request:          fixture.request,
			RequestCanonical: requestCanonical,
			Reply:            reply,
			ReplyCanonical:   mustCanonical(reply),
		})
	}
	return vectors
}

func writeFixture(dir, name string, value any, force bool) error {
	path := filepath.Join(dir, name)
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s exists; fixtures are frozen (use -force with a stated reason)", path)
		}
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

func main() {
	force := flag.Bool("force", false, "overwrite frozen fixtures (requires a stated reason in the commit)")
	dir := flag.String("dir", filepath.Join("..", "wire", "fixtures"), "fixture output directory")
	flag.Parse()

	types := buildTypes()
	chains := buildChains(types)
	frames := buildFrames(types)
	concierge := buildConcierge()

	for name, value := range map[string]any{
		"types.json":     types,
		"chains.json":    chains,
		"frames.json":    frames,
		"concierge.json": concierge,
	} {
		if err := writeFixture(*dir, name, value, *force); err != nil {
			fmt.Fprintf(os.Stderr, "wirefix: %v\n", err)
			os.Exit(1)
		}
	}
	fmt.Println("wirefix: fixtures written")
}
