// wirefix generates the golden byte fixtures in proto/wire/fixtures —
// ONCE, from the Go side (the fixture discipline: fixtures are
// evidence, generated by one side and frozen; both sides wall against
// them independently). It refuses to overwrite existing fixtures
// unless -force is given with a stated reason committed alongside.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nats-io/nats.go"

	"foldlab/canonical"
	"foldlab/proto/protod"
)

type typeVector struct {
	Name      string `json:"name"`
	Structure any    `json:"structure"`
	Canonical string `json:"canonical"`
	Digest    string `json:"digest"`
}

type chainVector struct {
	Name         string   `json:"name"`
	Payloads     []string `json:"payloads"`
	EntryDigests []string `json:"entryDigests"`
	Head         string   `json:"head"`
}

type frameVector struct {
	Name      string `json:"name"`
	Frame     any    `json:"frame"`
	Canonical string `json:"canonical"`
}

type conciergeVector struct {
	Name             string `json:"name"`
	Subject          string `json:"subject"`
	Request          any    `json:"request"`
	RequestCanonical string `json:"requestCanonical"`
	Reply            any    `json:"reply"`
	ReplyCanonical   string `json:"replyCanonical"`
}

type sessionStep struct {
	Step        int             `json:"step"`
	Event       json.RawMessage `json:"event"`
	Canonical   string          `json:"canonical"`
	Head        string          `json:"head"`
	StateDigest string          `json:"stateDigest"`
}

type sessionFixture struct {
	Provenance    string        `json:"_provenance"`
	Version       string        `json:"version"`
	GrammarDigest string        `json:"grammarDigest"`
	StateScheme   string        `json:"stateScheme"`
	Session       string        `json:"session"`
	Steps         []sessionStep `json:"steps"`
}

// The command is spelled without a shell conjunction on purpose: Go's JSON
// encoder escapes "&", and a provenance line nobody can read is a provenance
// line nobody can run.
const sessionsProvenance = "Generated by executing the daemon: from proto/go, run `go run ./cmd/wirefix -force`. " +
	"One flb.session.v0 dialogue (open, fill, fill, unfill, fill) is driven over NATS against a live protod; " +
	"each event is the exact canonical payload the daemon journaled, each head is the genesis-rooted chain " +
	"digest over those payloads, and each stateDigest is the daemon's own reply. The grammar digest is learned " +
	"from the daemon's own open refusal, never restated here. Oracle: the Go daemon — this is a single-implementation " +
	"pin that proto/ts/test/session-journal.test.ts walls independently. Domain: one dialogue over a root hole " +
	"filled to list/string, unfilled, and refilled to bool; nothing outside that dialogue is claimed."

func mustCanonical(value any) string {
	raw, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	bytes, err := canonical.Canonicalize(raw)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

func vector(name string, structure any) typeVector {
	c := mustCanonical(structure)
	return typeVector{
		Name:      name,
		Structure: structure,
		Canonical: c,
		Digest:    canonical.DigestHex([]byte(c)),
	}
}

func m(pairs ...any) map[string]any {
	out := map[string]any{}
	for i := 0; i < len(pairs); i += 2 {
		out[pairs[i].(string)] = pairs[i+1]
	}
	return out
}

func union(members ...any) map[string]any {
	sort.Slice(members, func(i, j int) bool {
		return mustCanonical(members[i]) < mustCanonical(members[j])
	})
	return m("k", "union", "of", members)
}

func buildTypes() []typeVector {
	str := m("k", "string")
	sensor := m(
		"k", "struct",
		"fields", m(
			"id", m("k", "brand", "name", "SensorId", "of", str),
			"reading", m("k", "opaque"),
			"count", m("k", "int"),
			"mode", union(
				m("k", "literal", "value", "on"),
				m("k", "literal", "value", "off"),
			),
			"note", str,
		),
		"optional", []any{"note"},
	)
	sensorDigest := canonical.DigestHex([]byte(mustCanonical(sensor)))

	return []typeVector{
		vector("leaf-string", str),
		vector("leaf-bool", m("k", "bool")),
		vector("leaf-int", m("k", "int")),
		vector("leaf-null", m("k", "null")),
		vector("literal-string", m("k", "literal", "value", "on")),
		vector("literal-number-normalizes", m("k", "literal", "value", 10.0)),
		vector("literal-bool", m("k", "literal", "value", true)),
		vector("literal-null", m("k", "literal", "value", nil)),
		vector("list-of-string", m("k", "list", "of", str)),
		// Field names sort by UTF-16 code units: "Z" < "a" < "é"
		vector("struct-utf16-key-order", m(
			"k", "struct",
			"fields", m("a", str, "Z", m("k", "int"), "é", m("k", "bool")),
			"optional", []any{"é"},
		)),
		vector("union", union(str, m("k", "null"))),
		vector("brand", m("k", "brand", "name", "UserId", "of", str)),
		vector("check-min-length", m(
			"k", "check", "base", str,
			"check", m("name", "minLength", "args", m("min", 1)),
		)),
		vector("opaque", m("k", "opaque")),
		vector("sensor-reading", sensor),
		vector("ref-with-check", m(
			"k", "check",
			"base", m("k", "ref", "digest", sensorDigest),
			"check", m("name", "minLength", "args", m("min", 1)),
		)),
		vector("string-escapes", m(
			"k", "struct",
			"fields", m("naïve \"quoted\"\n\ttab", str),
			"optional", []any{},
		)),
	}
}

func buildChains(types []typeVector) []chainVector {
	sensor := types[len(types)-3] // sensor-reading
	record := m(
		"digest", sensor.Digest,
		"scheme", "bytes-sha256-v1",
		"structure", sensor.Structure,
		"submitter", "wirefix",
	)
	framePayload := mustCanonical(m(
		"type", sensor.Digest,
		"payload", m("id", "s-1", "reading", 21.5, "count", 3, "mode", "on"),
	))

	simple := []string{"a", "b", "c"}
	simpleDigests, simpleHead := mustBuildChain(simple)

	catalogPayloads := []string{mustCanonical(record), framePayload}
	catalogDigests, catalogHead := mustBuildChain(catalogPayloads)

	return []chainVector{
		{Name: "simple", Payloads: simple, EntryDigests: simpleDigests, Head: simpleHead},
		{Name: "catalog-then-frame", Payloads: catalogPayloads, EntryDigests: catalogDigests, Head: catalogHead},
	}
}

func mustBuildChain(payloads []string) ([]string, string) {
	digests, head, err := canonical.BuildChain(payloads)
	if err != nil {
		panic(err)
	}
	return digests, head
}

func buildFrames(types []typeVector) []frameVector {
	sensor := types[len(types)-3]
	plain := m(
		"type", sensor.Digest,
		"payload", m("id", "s-1", "reading", 21.5, "count", 3, "mode", "on"),
	)
	tricky := m(
		"type", sensor.Digest,
		"payload", m(
			"id", "s-☃", // snowman: multibyte UTF-8
			"reading", 1.0, // JCS: serializes as "1"
			"count", 1000000, // stays plain notation
			"mode", "off",
			"note", "line\nbreak \"q\"",
		),
	)
	return []frameVector{
		{Name: "plain", Frame: plain, Canonical: mustCanonical(plain)},
		{Name: "unicode-and-number-normalization", Frame: tricky, Canonical: mustCanonical(tricky)},
	}
}

func buildConcierge() []conciergeVector {
	store, err := os.MkdirTemp("", "flb-wirefix-concierge-")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(store)

	daemon, err := protod.Acquire(context.Background(), protod.Options{
		StoreDir: store, SyncMode: protod.SyncCrashDurable,
	})
	if err != nil {
		panic(err)
	}
	defer daemon.Release()
	conn, err := nats.Connect(daemon.URL(), nats.Name("foldlab-wirefix/0.0.0/fixture-client"))
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	hole := m("k", "hole")
	listHole := m("k", "list", "of", hole)
	cases := []struct {
		name    string
		subject string
		request any
	}{
		{
			name:    "fill-bare-hole",
			subject: "flb.req.type.fill",
			request: m("partial", hole, "path", []any{}, "subtree", hole),
		},
		{
			name:    "fill-list-child",
			subject: "flb.req.type.fill",
			request: m("partial", listHole, "path", []any{"of"}, "subtree", m("k", "string")),
		},
		{
			name:    "unfill-list-child",
			subject: "flb.req.type.unfill",
			request: m(
				"partial", m("k", "list", "of", m("k", "string")),
				"path", []any{"of"},
			),
		},
		{
			name:    "fill-non-hole-refusal",
			subject: "flb.req.type.fill",
			request: m(
				"partial", m("k", "string"),
				"path", []any{},
				"subtree", m("k", "bool"),
			),
		},
		{
			name:    "fill-unknown-ref-refusal",
			subject: "flb.req.type.fill",
			request: m(
				"partial", hole,
				"path", []any{},
				"subtree", m("k", "ref", "digest", "9999999999999999999999999999999999999999999999999999999999999999"),
			),
		},
		{
			name:    "unfill-invalid-path-refusal",
			subject: "flb.req.type.unfill",
			request: m("partial", m("k", "string"), "path", []any{"of"}),
		},
	}

	vectors := make([]conciergeVector, 0, len(cases))
	for _, fixture := range cases {
		requestCanonical := mustCanonical(fixture.request)
		message, err := conn.Request(fixture.subject, []byte(requestCanonical), 20*time.Second)
		if err != nil {
			panic(err)
		}
		var reply any
		if err := json.Unmarshal(message.Data, &reply); err != nil {
			panic(err)
		}
		vectors = append(vectors, conciergeVector{
			Name:             fixture.name,
			Subject:          fixture.subject,
			Request:          fixture.request,
			RequestCanonical: requestCanonical,
			Reply:            reply,
			ReplyCanonical:   mustCanonical(reply),
		})
	}
	return vectors
}

// buildSessions drives one flb.session.v0 dialogue through a live daemon and
// records exactly what the daemon journaled: the canonical event payloads, the
// chain heads over them, and the daemon's own normalized state digests. No
// event is hand-written and no grammar is restated here — a restatement is the
// drift this fixture exists to catch.
func buildSessions() sessionFixture {
	store, err := os.MkdirTemp("", "flb-wirefix-sessions-")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(store)

	daemon, err := protod.Acquire(context.Background(), protod.Options{
		StoreDir: store, SyncMode: protod.SyncCrashDurable,
	})
	if err != nil {
		panic(err)
	}
	defer daemon.Release()
	conn, err := nats.Connect(daemon.URL(), nats.Name("foldlab-wirefix/0.0.0/fixture-client"))
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	author := "fixture-agent"
	grammar := learnSessionGrammar(conn)
	opened := mustFact(conn, protod.SubjectSessionOpen, m(
		"grammar", grammar,
		"seed", m("k", "hole"),
		"author", author,
	))
	session := mustString(opened, "session")
	head := mustString(opened, "head")
	stateDigests := []string{mustString(opened, "stateDigest")}

	moves := []map[string]any{
		m("op", "fill", "path", []any{}, "subtree", m("k", "list", "of", m("k", "hole"))),
		m("op", "fill", "path", []any{"of"}, "subtree", m("k", "string")),
		m("op", "unfill", "path", []any{"of"}),
		m("op", "fill", "path", []any{"of"}, "subtree", m("k", "bool")),
	}
	for _, move := range moves {
		body := m("session", session, "expectedHead", head, "principal", author)
		for key, value := range move {
			body[key] = value
		}
		state := mustFact(conn, protod.SubjectSessionMove, body)
		head = mustString(state, "head")
		stateDigests = append(stateDigests, mustString(state, "stateDigest"))
	}

	read := mustFact(conn, protod.SubjectJournalRead, m("journal", session))
	entries, ok := read["entries"].([]any)
	if !ok || len(entries) != len(stateDigests) {
		panic(fmt.Sprintf("wirefix: session journal returned %d entries, want %d", len(entries), len(stateDigests)))
	}
	payloads := make([]string, len(entries))
	for index, item := range entries {
		entry, ok := item.(map[string]any)
		if !ok {
			panic("wirefix: session journal entry is not an object")
		}
		payloads[index] = mustString(entry, "payload")
	}
	// Heads are claims (W6): re-derive the chain locally and require the
	// daemon's claimed head to equal the last derived digest.
	heads, chainHead := mustBuildChain(payloads)
	if chainHead != head {
		panic(fmt.Sprintf("wirefix: derived session head %s, daemon claimed %s", chainHead, head))
	}

	steps := make([]sessionStep, len(payloads))
	for index, payload := range payloads {
		steps[index] = sessionStep{
			Step:        index,
			Event:       json.RawMessage(payload),
			Canonical:   payload,
			Head:        heads[index],
			StateDigest: stateDigests[index],
		}
	}
	var open map[string]any
	if err := json.Unmarshal([]byte(payloads[0]), &open); err != nil {
		panic(err)
	}
	return sessionFixture{
		Provenance:    sessionsProvenance,
		Version:       mustString(open, "version"),
		GrammarDigest: grammar,
		StateScheme:   mustString(opened, "stateScheme"),
		Session:       session,
		Steps:         steps,
	}
}

// learnSessionGrammar asks the daemon for its own grammar digest the only way
// a client can: open under a digest the daemon cannot hold and read the exact
// value its teaching refusal expects (W7 — refusals carry enough for
// self-repair). A generator that recomputed the descriptor here would become
// the fifteenth restatement of the grammar.
func learnSessionGrammar(conn *nats.Conn) string {
	reply := mustReply(conn, protod.SubjectSessionOpen, m(
		"grammar", strings.Repeat("0", 64),
		"seed", m("k", "hole"),
		"author", "wirefix-grammar-probe",
	))
	refusal, ok := reply["refusal"].(map[string]any)
	if !ok {
		panic("wirefix: session.open under an unknown grammar did not refuse")
	}
	expected := mustString(refusal, "expected")
	if len(expected) != 64 {
		panic("wirefix: session.open refusal did not teach a grammar digest")
	}
	return expected
}

func mustReply(conn *nats.Conn, subject string, body any) map[string]any {
	message, err := conn.Request(subject, []byte(mustCanonical(body)), 20*time.Second)
	if err != nil {
		panic(err)
	}
	var reply map[string]any
	if err := json.Unmarshal(message.Data, &reply); err != nil {
		panic(err)
	}
	return reply
}

func mustFact(conn *nats.Conn, subject string, body any) map[string]any {
	reply := mustReply(conn, subject, body)
	if ok, _ := reply["ok"].(bool); !ok {
		panic(fmt.Sprintf("wirefix: %s refused: %s", subject, mustCanonical(reply)))
	}
	return reply
}

func mustString(object map[string]any, key string) string {
	value, ok := object[key].(string)
	if !ok {
		panic(fmt.Sprintf("wirefix: %q is not a string in %s", key, mustCanonical(object)))
	}
	return value
}

func writeFixture(dir, name string, value any, force bool) error {
	path := filepath.Join(dir, name)
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s exists; fixtures are frozen (use -force with a stated reason)", path)
		}
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// fixtureNames is the family this generator owns, in a fixed order. The
// regeneration gate reads it, so a fixture added here without a committed
// counterpart — or a committed fixture dropped from here — is a gate failure
// rather than a silent gap.
func fixtureNames() []string {
	return []string{"types.json", "chains.json", "frames.json", "concierge.json", "sessions.json"}
}

// generate is the whole of the command's work, so the regeneration gate runs
// the generator rather than a re-implementation of it. main() adds only flag
// parsing.
func generate(dir string, force bool) error {
	types := buildTypes()
	values := map[string]any{
		"types.json":     types,
		"chains.json":    buildChains(types),
		"frames.json":    buildFrames(types),
		"concierge.json": buildConcierge(),
		"sessions.json":  buildSessions(),
	}
	for _, name := range fixtureNames() {
		if err := writeFixture(dir, name, values[name], force); err != nil {
			return err
		}
	}
	return nil
}

func main() {
	force := flag.Bool("force", false, "overwrite frozen fixtures (requires a stated reason in the commit)")
	dir := flag.String("dir", filepath.Join("..", "wire", "fixtures"), "fixture output directory")
	flag.Parse()

	if err := generate(*dir, *force); err != nil {
		fmt.Fprintf(os.Stderr, "wirefix: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wirefix: fixtures written")
}
