// Command kmgen emits the Go type layer of foldlab/kmconform from the kernel
// model's conformance corpus.
//
// Nothing in the generated file is typed by hand. Every kind, every stage,
// every refusal law, every taught repair, every applicability mark, every
// brand, every docstring, and every vector is read out of the artifact and
// written into Go. That is the whole discipline: a table a human retypes has
// forked the model the moment the model changes, and the fork is invisible
// until something downstream is already wrong.
//
// Run from the module root:
//
//	go run ./cmd/kmgen          # rewrite kmconform/tables_generated.go
//	go run ./cmd/kmgen -check   # refuse if the committed file is not a fresh emission
//
// The corpus it reads is whatever kmconform.ConformanceCorpusPath names, so
// the one-line switch from the transitional sample to the model-emitted
// artifact moves this generator with it and nothing else has to be edited.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"math/big"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"foldlab/kmconform"
)

// generatedFile is where the emission lands, relative to the module root.
const generatedFile = "kmconform/tables_generated.go"

func corpusPathFrom(root string) string {
	return filepath.Join(root, "kmconform", kmconform.ConformanceCorpusPath)
}

func generatedPathFrom(root string) string {
	return filepath.Join(root, generatedFile)
}

func main() {
	root := flag.String("root", ".", "the module root to read the corpus from and write the emission to")
	check := flag.Bool("check", false, "refuse if the committed emission is not what this generator produces")
	flag.Parse()

	emitted, err := generate(corpusPathFrom(*root))
	if err != nil {
		fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
		os.Exit(1)
	}
	target := generatedPathFrom(*root)
	if *check {
		committed, err := os.ReadFile(target)
		if err != nil {
			fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
			os.Exit(1)
		}
		if !bytes.Equal(committed, emitted) {
			fmt.Fprintf(os.Stderr,
				"REFUSED: %s is not a fresh emission (committed %d bytes, regenerated %d). "+
					"The committed bytes are the record of the old behaviour; report the drift, do not overwrite it.\n",
				target, len(committed), len(emitted))
			os.Exit(1)
		}
		fmt.Printf("%s is a fresh emission (%d bytes)\n", target, len(emitted))
		return
	}
	if err := os.WriteFile(target, emitted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d bytes)\n", target, len(emitted))
}

// generate reads the corpus, validates it through the same consumer every
// other reader uses, and writes the Go source. It refuses on anything the
// validator refuses: a generator that is more tolerant than its own consumer
// would bake a defect into compiled code.
func generate(corpusPath string) ([]byte, error) {
	raw, err := os.ReadFile(corpusPath)
	if err != nil {
		return nil, err
	}
	corpus, err := kmconform.CheckBothWays(raw)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", corpusPath, err)
	}
	if skipped := corpus.SkipLog(); len(skipped) > 0 {
		return nil, fmt.Errorf(
			"the corpus carries record types this generator does not know, so the emission would be "+
				"silently incomplete: %s", strings.Join(skipped, "; "))
	}

	if err := checkIdentifiers(corpus); err != nil {
		return nil, err
	}
	var out strings.Builder
	if err := writeSource(&out, corpus); err != nil {
		return nil, err
	}
	// gofmt-canonical by construction, so a routine format pass can never
	// change the committed bytes (schema §11 check 32).
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("the emission is not valid Go: %w", err)
	}
	return formatted, nil
}

func writeSource(out *strings.Builder, corpus *kmconform.Corpus) error {
	writeBanner(out, corpus)
	writeDeclKind(out, corpus)
	writeHoleStage(out, corpus)
	writeApplicability(out)
	writeRefusals(out, corpus)
	writeBrands(out, corpus)
	writeValueLevelBrands(out)
	writeTypeNames(out, corpus)
	writeDocs(out, corpus)
	if err := writeEncodings(out, corpus); err != nil {
		return err
	}
	if err := writeAdmissions(out, corpus); err != nil {
		return err
	}
	writePrograms(out, corpus)
	return nil
}

func writeBanner(out *strings.Builder, corpus *kmconform.Corpus) {
	fmt.Fprintf(out, `// Code generated by cmd/kmgen from %s. DO NOT EDIT.
//
// Every table below is the model's, read out of the conformance corpus and
// written into Go mechanically. Edit the model, re-emit the corpus, re-run
// the generator; editing this file forks the model instead.
//
// What these tables are, and are not: they carry the MODEL'S VERDICTS. They
// do not promote the model's theorems into guarantees about any running
// system. A conforming consumer refuses the same candidates for the same
// reasons and encodes the same acts the same way, and nothing more than that
// should be read into a green conformance run.

package kmconform

import "fmt"

// The provenance of the tables in this file. Display data: no behaviour
// branches on it.
const (
	Source       = %s
	Generator    = %s
	CorpusFormat = %d
)

`, kmconform.ConformanceCorpusPath,
		strconv.Quote(corpus.Header.Source),
		strconv.Quote(corpus.Header.Generator),
		corpus.Header.Format)
}

func writeDeclKind(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// DeclKind is the closed universe of declaration kinds. The numeric value
// is the model's rank, so it is wire-stable within a format.
type DeclKind uint8

const (
`)
	for _, row := range corpus.Kinds {
		fmt.Fprintf(out, "\t%s DeclKind = %d\n", "Kind"+exportedIdent(row.Name), row.Rank)
	}
	out.WriteString(")\n\nvar declKindNames = [...]string{\n")
	for _, row := range corpus.Kinds {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(row.Name))
	}
	out.WriteString(`}

func (k DeclKind) String() string {
	if int(k) >= len(declKindNames) {
		return fmt.Sprintf("DeclKind(%d)", uint8(k))
	}
	return declKindNames[k]
}

// DeclKindFromRank is the decode half of the rank. An out-of-range rank is
// refused, never saturated: a decoder that clamps turns a wire defect into a
// plausible wrong answer.
func DeclKindFromRank(rank uint8) (DeclKind, bool) {
	if int(rank) >= len(declKindNames) {
		return 0, false
	}
	return DeclKind(rank), true
}

// DeclKindByName resolves a wire name. Unknown names are refused.
func DeclKindByName(name string) (DeclKind, bool) {
	for rank, known := range declKindNames {
		if known == name {
			return DeclKind(rank), true
		}
	}
	return 0, false
}

`)
}

func writeHoleStage(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// HoleStage is the epistemic stage of a hole, in rising rank order.
type HoleStage uint8

const (
`)
	for _, row := range corpus.Stages {
		fmt.Fprintf(out, "\t%s HoleStage = %d\n", "Stage"+exportedIdent(row.Name), row.Rank)
	}
	out.WriteString(")\n\nvar holeStageNames = [...]string{\n")
	for _, row := range corpus.Stages {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(row.Name))
	}
	out.WriteString(`}

func (s HoleStage) String() string {
	if int(s) >= len(holeStageNames) {
		return fmt.Sprintf("HoleStage(%d)", uint8(s))
	}
	return holeStageNames[s]
}

// Reached reports whether s is at least target. A hole production observes
// rank only in the reached-at-least direction.
func (s HoleStage) Reached(target HoleStage) bool { return s >= target }

// HoleStageFromRank refuses an out-of-range rank rather than saturating.
func HoleStageFromRank(rank uint8) (HoleStage, bool) {
	if int(rank) >= len(holeStageNames) {
		return 0, false
	}
	return HoleStage(rank), true
}

`)
}

func writeApplicability(out *strings.Builder) {
	out.WriteString(`// Applicability marks whether a taught repair is a function of the refused
// candidate alone. The machine-applicable half is what tells an agent it may
// apply the repair without asking, so the mark has to survive to the caller
// or the taught table is only prose.
type Applicability uint8

const (
	MachineApplicable Applicability = iota
	Advisory
)

func (a Applicability) String() string {
	if a == MachineApplicable {
		return "machine-applicable"
	}
	return "advisory"
}

`)
}

func writeRefusals(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// RefusalReason indexes the taught table. The numeric value is this table's
// position, which is the model's RefusalReason declaration order; compare by
// Wire when crossing a version boundary.
type RefusalReason uint8

const (
`)
	for index, row := range corpus.Refusals {
		fmt.Fprintf(out, "\t%s RefusalReason = %d\n", "Reason"+exportedIdent(row.Reason), index)
	}
	out.WriteString(`)

// Refusal is one row of the taught table: the reason, the law it defends, the
// taught repair, and how the repair may be applied. The door never refuses
// without teaching the legal next move, so no field here is optional.
type Refusal struct {
	Reason        RefusalReason
	Wire          string
	Law           string
	Repair        string
	Applicability Applicability
}

// RefusalTable is the taught table in the model's declaration order.
var RefusalTable = [...]Refusal{
`)
	for index, row := range corpus.Refusals {
		applicability := "Advisory"
		if row.Applicability == "machine-applicable" {
			applicability = "MachineApplicable"
		}
		fmt.Fprintf(out, `	{
		Reason:        %d,
		Wire:          %s,
		Law:           %s,
		Repair:        %s,
		Applicability: %s,
	},
`, index, strconv.Quote(row.Reason), strconv.Quote(row.Law), strconv.Quote(row.Repair), applicability)
	}
	out.WriteString(`}

// Taught returns the row a reason carries. Total by construction: a reason
// without its law and its repair cannot exist in this table.
func Taught(r RefusalReason) Refusal { return RefusalTable[r] }

// RefusalByWire resolves a wire reason. Unknown reasons are refused, never
// defaulted to a neighbouring row.
func RefusalByWire(wire string) (RefusalReason, bool) {
	for index := range RefusalTable {
		if RefusalTable[index].Wire == wire {
			return RefusalReason(index), true
		}
	}
	return 0, false
}

// RefusalError carries a taught refusal as a Go error, so the model's taught
// table becomes this package's caller-facing diagnostic vocabulary rather
// than a lookup a caller has to remember to perform.
type RefusalError struct{ Refusal Refusal }

func (e RefusalError) Error() string {
	return e.Refusal.Wire + ": " + e.Refusal.Law + " [repair: " + e.Refusal.Repair + "]"
}

// Refuse mints the error for a reason.
func Refuse(r RefusalReason) error { return RefusalError{Taught(r)} }

// MachineApplicableRepairs is the codemod catalog: the repairs that are a
// function of the refused candidate alone.
func MachineApplicableRepairs() []Refusal {
	catalog := make([]Refusal, 0, len(RefusalTable))
	for _, row := range RefusalTable {
		if row.Applicability == MachineApplicable {
			catalog = append(catalog, row)
		}
	}
	return catalog
}

`)
}

func writeBrands(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// ---- Brand types ----
//
// The model brands a digest by the kind of declaration it names, and the
// comparison of two differently branded digests HAS NO TYPE: the Lean
// elaborator refuses it, so there is nothing to write. Go's nearest
// equivalent is one defined type per kind, which makes the cross-kind
// comparison a compile error.
//
// What the defined type does NOT buy, stated plainly rather than left for a
// reader to discover:
//
//   - an untyped constant adopts any brand, so ` + "`d == 3`" + ` compiles;
//   - an explicit conversion crosses any brand, silently and always;
//   - a value-level brand (the register that issued a token) has no type to
//     become, because Go has no dependent types, so it rides as data and the
//     elaborator's refusal becomes the run-time check below.
//
// The first two are closed mechanically by foldlab/brandlint, which reads the
// //foldlab:brand directives on these declarations. The third is not closed
// at all: a caller who drops the returned error gets nothing.

`)
	for _, row := range corpus.Kinds {
		name := exportedIdent(row.Name) + "Digest"
		fmt.Fprintf(out, "//foldlab:brand %s\ntype %s uint64\n\n", row.Name, name)
	}
	out.WriteString(`// The constructor discipline: a digest is minted from a resolved identifier
// through a named function, never conjured from an integer at a call site.
// Nothing mints a name.
`)
	for _, row := range corpus.Kinds {
		name := exportedIdent(row.Name) + "Digest"
		fmt.Fprintf(out, "func New%s(id uint64) %s { return %s(id) }\n", name, name, name)
	}
	out.WriteString("\n// BrandTypeNames lists the brands this package declares, so a lint that\n" +
		"// runs over a CONSUMER of this package can be told the brand set without\n" +
		"// re-deriving it from the corpus.\nvar BrandTypeNames = []string{\n")
	for _, row := range corpus.Kinds {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(exportedIdent(row.Name)+"Digest"))
	}
	out.WriteString("}\n\n")
}

func writeValueLevelBrands(out *strings.Builder) {
	out.WriteString(`// ---- Value-level brands ----
//
// In the model a token's register and a position's partition are part of the
// TYPE, so a cross-register spend and a cross-partition compare fail to
// elaborate. Go cannot index a type by a value, so the brand rides as
// unexported data and the refusal moves from compile time to run time. That
// is a real loss and not a workaround that recovers the property.

// Token is a lease, meaningful only at the register that issued it.
type Token struct {
	register ProgramDigest
	value    uint64
}

// NewToken pins the issuing register at construction, so a token with no
// register cannot be built.
func NewToken(register ProgramDigest, value uint64) Token {
	return Token{register: register, value: value}
}

// Register reports which register issued the token.
func (t Token) Register() ProgramDigest { return t.register }

// Spend refuses a token presented at a register that did not issue it. In
// the model this refusal is a type error; here it is an error value, and a
// caller who discards it has the guarantee of neither.
func (t Token) Spend(register ProgramDigest) (uint64, error) {
	if t.register != register {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	return t.value, nil
}

// LanePartition is the venue-local shard of an evidence stream.
type LanePartition struct {
	Lane  LaneDigest
	Shard uint64
}

// Position is a journal position, meaningful only within its partition.
type Position struct {
	partition LanePartition
	value     uint64
}

// NewPosition pins the partition at construction.
func NewPosition(partition LanePartition, value uint64) Position {
	return Position{partition: partition, value: value}
}

// Partition reports the partition a position is denominated in.
func (p Position) Partition() LanePartition { return p.partition }

// Compare refuses two positions denominated in different partitions — the
// proven-but-vacuous comparison the model gives no syntax for.
func (p Position) Compare(other Position) (int, error) {
	if p.partition != other.partition {
		return 0, Refuse(ReasonCrossSortIdentifier)
	}
	switch {
	case p.value < other.value:
		return -1, nil
	case p.value > other.value:
		return 1, nil
	default:
		return 0, nil
	}
}

`)
}

func writeTypeNames(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString("// TypeNames is the closed type list in the model's declaration order.\nvar TypeNames = []string{\n")
	for _, row := range corpus.Types {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(row.Name))
	}
	out.WriteString("}\n\n")
}

func writeDocs(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// ---- Docstrings ----
//
// The model's own prose, extracted from its environment and carried here
// verbatim. It is the text a generated schema annotation publishes as a
// parameter description, which is how a sentence written once in the model
// reaches an agent with no human in the path — and why a hand-edited copy is
// a wrong answer rather than a typo.

// DocEntry is one type's docstring.
type DocEntry struct {
	Name string
	Doc  string
}

// DocTable is the doc group in type declaration order.
var DocTable = []DocEntry{
`)
	for _, row := range corpus.Docs {
		fmt.Fprintf(out, "\t{Name: %s, Doc: %s},\n", strconv.Quote(row.Name), strconv.Quote(row.Doc))
	}
	out.WriteString(`}

// DocFor resolves a type's docstring. A type without one is reported as
// absent rather than as an empty string, so a caller cannot render a blank
// description and believe it is the model's.
func DocFor(name string) (string, bool) {
	for _, entry := range DocTable {
		if entry.Name == name {
			return entry.Doc, true
		}
	}
	return "", false
}

`)
}

func writeEncodings(out *strings.Builder, corpus *kmconform.Corpus) error {
	out.WriteString(`// ---- Conformance vectors ----
//
// The model's own outputs. A consumer tests its door against them verdict for
// verdict. They check an implementation against the model's verdicts; they do
// not promote the model's theorems into runtime guarantees.

// EncodingVector is one canonical sentence framing.
type EncodingVector struct {
	Name string
	Act  []uint64
}

// EncodingVectors is the encoding group in corpus order.
//
// The wire number domain is the unbounded non-negative integers and the
// parser reads it at arbitrary precision. This table is a checked-width
// convenience: kmgen REFUSES to emit a vector that does not fit a uint64
// rather than truncating one, so a corpus that outgrows the width fails
// generation loudly instead of shipping a rounded act.
var EncodingVectors = []EncodingVector{
`)
	for _, row := range corpus.Encodings {
		literal, err := uint64List(row.Act, "encoding vector "+row.Name)
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "\t{Name: %s, Act: %s},\n", strconv.Quote(row.Name), literal)
	}
	out.WriteString(`}

// EncodingVectorByName resolves a vector. Unknown names are refused.
func EncodingVectorByName(name string) (EncodingVector, bool) {
	for _, vector := range EncodingVectors {
		if vector.Name == name {
			return vector, true
		}
	}
	return EncodingVector{}, false
}

`)
	return nil
}

func writeAdmissions(out *strings.Builder, corpus *kmconform.Corpus) error {
	out.WriteString(`// AdmissionVector is one planted candidate and the door's verdict. The
// admitted row is what stops the suite from being satisfied by a door that
// refuses everything.
type AdmissionVector struct {
	Name     string
	Admitted bool
	Reason   string
	Encoded  []uint64
}

// AdmissionVectors is the admission group in the kernel gate's control order.
var AdmissionVectors = []AdmissionVector{
`)
	for _, row := range corpus.Admissions {
		if row.Verdict == "admitted" {
			literal, err := uint64List(row.Encoded, "admission vector "+row.Name)
			if err != nil {
				return err
			}
			fmt.Fprintf(out, "\t{Name: %s, Admitted: true, Encoded: %s},\n",
				strconv.Quote(row.Name), literal)
			continue
		}
		fmt.Fprintf(out, "\t{Name: %s, Reason: %s},\n",
			strconv.Quote(row.Name), strconv.Quote(row.Reason))
	}
	out.WriteString("}\n")
	return nil
}

func writePrograms(out *strings.Builder, corpus *kmconform.Corpus) {
	out.WriteString(`// ---- Program vectors ----
//
// The ninth corpus group: the DAG builder's committed declarations, each with
// the canonical bytes it serializes to.
//
// WHY BYTES AND NOT THE DECLARATION. The declaration already has a Go form —
// kmconform.ProgramDeclaration, hand-written and conformance-walled — and
// emitting a second Go spelling of the same grammar here would be two
// spellings of one thing, which is the exact defect generation exists to
// prevent. What a consumer actually needs from a table is the model's answer
// to compare its own construction against, and that answer is a byte string.
// It is the same reasoning that puts canonical examples on the TypeScript
// surface as strings rather than as values.
//
// These are DECLARATIONS, never execution records. Nothing here runs.

// ProgramVector is one committed program declaration, named, with the
// canonical serialization the corpus carries for it.
type ProgramVector struct {
	Name  string
	Bytes string
}

// ProgramVectorTable is the program group in corpus order.
var ProgramVectorTable = []ProgramVector{
`)
	for _, row := range corpus.Programs {
		fmt.Fprintf(out, "\t{Name: %s, Bytes: %s},\n",
			strconv.Quote(row.Name), strconv.Quote(row.Bytes))
	}
	out.WriteString(`}

// ProgramVectorNames is the committed vector names in corpus order.
var ProgramVectorNames = []string{
`)
	for _, row := range corpus.Programs {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(row.Name))
	}
	out.WriteString(`}

// ProgramVectorByName resolves a vector. Unknown names are refused.
func ProgramVectorByName(name string) (ProgramVector, bool) {
	for _, vector := range ProgramVectorTable {
		if vector.Name == name {
			return vector, true
		}
	}
	return ProgramVector{}, false
}
`)
}

// uint64List renders a Nat sequence as a Go literal, refusing any value that
// does not fit the width rather than wrapping or saturating it.
func uint64List(numbers []*big.Int, what string) (string, error) {
	parts := make([]string, 0, len(numbers))
	for index, number := range numbers {
		if !number.IsUint64() {
			return "", fmt.Errorf(
				"%s element %d is %s, which does not fit a uint64: the wire domain is unbounded, so this "+
					"table's checked width has been outgrown and the generated type must move to *big.Int",
				what, index, number)
		}
		parts = append(parts, strconv.FormatUint(number.Uint64(), 10))
	}
	return "[]uint64{" + strings.Join(parts, ", ") + "}", nil
}

// exportedIdent turns a wire name into an exported Go identifier:
// "clock-read" becomes "ClockRead", "schema" becomes "Schema". The mapping is
// total over the corpus's names, and a name it cannot render is a generation
// failure rather than a mangled identifier.
func exportedIdent(wire string) string {
	parts := strings.FieldsFunc(wire, func(r rune) bool { return r == '-' || r == '_' || r == ' ' })
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]))
		out.WriteString(part[1:])
	}
	return out.String()
}

// checkIdentifiers refuses a corpus whose names would collide once rendered
// as Go identifiers — "clock-read" and "clock_read" both become ClockRead.
// The generator owns this check because the alternative is a compile error in
// a generated file, which reports the symptom at the wrong layer and leaves a
// half-written emission on disk.
func checkIdentifiers(corpus *kmconform.Corpus) error {
	minted := map[string]string{}
	claim := func(identifier, origin string) error {
		if identifier == "" {
			return fmt.Errorf("%s renders as an empty Go identifier", origin)
		}
		if previous, taken := minted[identifier]; taken {
			return fmt.Errorf(
				"the identifier %s would be minted from both %s and %s; the corpus names collide once "+
					"rendered as Go", identifier, previous, origin)
		}
		minted[identifier] = origin
		return nil
	}
	for _, row := range corpus.Kinds {
		if err := claim("Kind"+exportedIdent(row.Name), "kind "+row.Name); err != nil {
			return err
		}
		if err := claim(exportedIdent(row.Name)+"Digest", "kind "+row.Name); err != nil {
			return err
		}
	}
	for _, row := range corpus.Stages {
		if err := claim("Stage"+exportedIdent(row.Name), "stage "+row.Name); err != nil {
			return err
		}
	}
	for _, row := range corpus.Refusals {
		if err := claim("Reason"+exportedIdent(row.Reason), "refusal "+row.Reason); err != nil {
			return err
		}
	}
	return nil
}
