import { resolve } from "node:path"

import {
  emitDeclarations,
  inspectPublicDeclarations,
} from "./public-effect-declarations.js"

const packageRoot = resolve(import.meta.dir, "..")
const manifestPath = resolve(packageRoot, "test/PublicEffects.signatures.txt")
const provenance = "# Generated by: bun run generate:public-effects\n"
const authority = "# Authority: emitted declarations own public values, members authored in this package's src, prototypes, Context.Service shapes, string/number indices, and every call/construct signature; the type-level walk is load-bearing for members authored outside this package's src.\n"
const normalize = (text: string): string =>
  text.replaceAll("\\", "/").replaceAll("\r\n", "\n")

const emitted = emitDeclarations("tsconfig.public-declarations.json")
let failed = false
try {
  const inspected = inspectPublicDeclarations(emitted.directory, "src/index.d.ts")
  const signatures = normalize(inspected.manifest)
  if (inspected.violations !== "") {
    console.error(inspected.violations)
    console.error("PUBLIC EFFECT GATE: FAIL — emitted public declarations carry non-Refusal errors")
    failed = true
  } else if (signatures.trim() === "") {
    console.error("PUBLIC EFFECT GATE: FAIL — emitted signature manifest is empty")
    failed = true
  } else {
    const manifest = Bun.file(manifestPath)
    const actual = provenance + authority + signatures
    if (process.argv.includes("--write")) {
      await Bun.write(manifestPath, actual)
      console.log("PUBLIC EFFECT GATE: wrote generated signature manifest")
    } else {
      const expected = await manifest.exists() ? normalize(await manifest.text()) : ""
      if (actual !== expected) {
        console.error("PUBLIC EFFECT GATE: FAIL — generated signature manifest moved")
        console.error("--- expected ---")
        console.error(expected)
        console.error("--- actual ---")
        console.error(actual)
        failed = true
      }

      if (!failed) {
        const count = signatures.trimEnd().split("\n").length
        console.log(`PUBLIC EFFECT GATE: PASS (${count} emitted signatures inspected)`)
      }
    }
  }
} finally {
  emitted.dispose()
}
if (failed) process.exit(1)
