/**
 * The taught-payload diff wall.
 *
 * A refusal's vocabulary is only half of what it teaches. The other half is
 * the payload: the law it defends, the expectation it names, and the repair
 * steps it hands back. Those texts are persisted evidence — they are read by
 * operators, matched by tooling, and quoted in tickets — so a change to one is
 * a change to the package's behaviour even when no type moves and every test
 * still passes.
 *
 * This module walks every object literal under `src/` that carries a `law`
 * field, which is what a minted refusal payload is, and renders its taught
 * texts into a manifest. The manifest is committed and byte-compared, so the
 * wall reddens on any edit to any minting site's teaching, and the diff it
 * prints is the edit itself.
 *
 * Payloads are keyed by file and by ordinal within the file rather than by
 * line, so an unrelated edit above a payload does not move it. Adding,
 * removing, or reordering a payload does move it, which is the event the wall
 * exists to show.
 *
 * A field whose value is not a literal renders as `<expression>`: the wall
 * pins what is written down as text, and claims nothing about what a computed
 * value evaluates to.
 *
 * @module
 */
import { readdirSync } from "node:fs"
import { resolve } from "node:path"

import * as ts from "typescript-five"

/** The result of comparing committed manifest bytes with a fresh walk. */
export type TaughtPayloadCheck =
  | { readonly ok: true; readonly payloads: number }
  | { readonly ok: false; readonly reason: string }

/** The command a reader runs to reproduce the committed manifest. */
export const GENERATE_COMMAND = "bun run generate:refusal-payloads"

/** The tree walked for taught payloads, relative to the repository root. */
export const SOURCE_ROOT = "packages/plait/src"

/** Where the manifest is committed, relative to the repository root. */
export const MANIFEST_PATH = "packages/plait/test/RefusalPayloads.taught.txt"

/** The field whose presence marks an object literal as a candidate payload. */
export const PAYLOAD_MARKER = "law"

/**
 * One of these must accompany the marker for the literal to be a payload.
 *
 * `law` alone is not enough: the kernel corpus schemas declare a `law` field on
 * the model's own taught-refusal record, and those declarations are generated
 * from the corpus and already walled where the emitter runs. A refusal
 * payload is the literal a minting site hands to the constructor, so it also
 * carries at least one of the constructor's other fields.
 */
export const PAYLOAD_COMPANIONS = ["kind", "path", "got", "expected", "next"] as const

/** The taught fields pinned on every payload, in the order they are rendered. */
export const TAUGHT_FIELDS = ["kind", "law", "expected"] as const

/** How a value that is not written down as a literal renders. */
export const NON_LITERAL = "<expression>"

/** How a field the payload does not carry renders. */
export const ABSENT = "<absent>"

const provenance = `# Generated by: ${GENERATE_COMMAND}\n`
const authority =
  `# Authority: every object literal under ${SOURCE_ROOT} carrying a \`${PAYLOAD_MARKER}\` field is a taught refusal payload; its kind, law, expected, and next texts are pinned here byte for byte, so an edit to any minting site's teaching reddens this wall.\n`

const normalize = (path: string): string => path.replaceAll("\\", "/")

/** Every TypeScript source under the walked tree, in a stable order. */
export const sourceFiles = (root: string): ReadonlyArray<string> => {
  const found: Array<string> = []
  const visit = (directory: string, prefix: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true }).sort(
      (left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
    )) {
      const path = prefix === "" ? entry.name : `${prefix}/${entry.name}`
      if (entry.isDirectory()) visit(resolve(directory, entry.name), path)
      else if (entry.isFile() && entry.name.endsWith(".ts")) found.push(path)
    }
  }
  visit(root, "")
  return found
}

/**
 * Every `const` in one file, by name.
 *
 * Minting sites name their shared teaching — `envelopeShapeLaw`,
 * `teachSupersededLease` — so a wall that stopped at the identifier would pin
 * the name and miss the text. Resolution is per file and first-declaration
 * wins, which is enough for a wall: a name that resolves to the wrong
 * declaration renders a text that is still pinned, and a name that resolves to
 * nothing renders `<expression>`.
 */
export type Bindings = ReadonlyMap<string, ts.Expression>

const bindingsOf = (file: ts.SourceFile): Bindings => {
  const bindings = new Map<string, ts.Expression>()
  const visit = (node: ts.Node): void => {
    if (
      ts.isVariableDeclaration(node)
      && ts.isIdentifier(node.name)
      && node.initializer !== undefined
      && !bindings.has(node.name.text)
    ) {
      bindings.set(node.name.text, node.initializer)
    }
    ts.forEachChild(node, visit)
  }
  visit(file)
  return bindings
}

/**
 * The hole a template's substitution renders as. A taught text built around a
 * runtime value still has fixed spans, and those spans are what this wall
 * pins; the hole marks where the value goes without claiming what it is.
 */
export const HOLE = "${}"

/** Follows aliases, assertions, parentheses, and zero-argument thunks. */
const resolve_ = (
  node: ts.Expression,
  bindings: Bindings,
  seen: ReadonlySet<string>,
): { readonly node: ts.Expression; readonly seen: ReadonlySet<string> } => {
  if (ts.isParenthesizedExpression(node)) return resolve_(node.expression, bindings, seen)
  if (ts.isAsExpression(node)) return resolve_(node.expression, bindings, seen)
  if (ts.isArrowFunction(node) && node.parameters.length === 0 && !ts.isBlock(node.body)) {
    return resolve_(node.body, bindings, seen)
  }
  if (ts.isIdentifier(node) && !seen.has(node.text)) {
    const bound = bindings.get(node.text)
    if (bound !== undefined) return resolve_(bound, bindings, new Set([...seen, node.text]))
  }
  return { node, seen }
}

const literalText = (
  expression: ts.Expression,
  bindings: Bindings,
  seen: ReadonlySet<string> = new Set(),
): string | undefined => {
  const { node, seen: followed } = resolve_(expression, bindings, seen)
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) return node.text
  if (ts.isTemplateExpression(node)) {
    let text = node.head.text
    for (const span of node.templateSpans) text += HOLE + span.literal.text
    return text
  }
  if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    const left = literalText(node.left, bindings, followed)
    const right = literalText(node.right, bindings, followed)
    return left === undefined || right === undefined ? undefined : left + right
  }
  return undefined
}

const property = (
  literal: ts.ObjectLiteralExpression,
  name: string,
): ts.Expression | undefined => {
  for (const member of literal.properties) {
    if (!ts.isPropertyAssignment(member)) continue
    const key = member.name
    const spelled = ts.isIdentifier(key) || ts.isStringLiteral(key) ? key.text : undefined
    if (spelled === name) return member.initializer
  }
  return undefined
}

const literalJson = (
  expression: ts.Expression,
  bindings: Bindings,
  seen: ReadonlySet<string> = new Set(),
): string | undefined => {
  const text = literalText(expression, bindings, seen)
  if (text !== undefined) return JSON.stringify(text)
  const { node, seen: followed } = resolve_(expression, bindings, seen)
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "true"
  if (node.kind === ts.SyntaxKind.FalseKeyword) return "false"
  if (node.kind === ts.SyntaxKind.NullKeyword) return "null"
  if (ts.isNumericLiteral(node)) return node.text
  if (
    ts.isPrefixUnaryExpression(node)
    && node.operator === ts.SyntaxKind.MinusToken
    && ts.isNumericLiteral(node.operand)
  ) {
    return `-${node.operand.text}`
  }
  if (ts.isArrayLiteralExpression(node)) {
    const rendered: Array<string> = []
    for (const element of node.elements) {
      if (!ts.isExpression(element)) return undefined
      const value = literalJson(element, bindings, followed)
      if (value === undefined) return undefined
      rendered.push(value)
    }
    return `[${rendered.join(",")}]`
  }
  if (ts.isObjectLiteralExpression(node)) {
    const rendered: Array<string> = []
    for (const member of node.properties) {
      if (!ts.isPropertyAssignment(member)) return undefined
      const key = member.name
      const spelled = ts.isIdentifier(key) || ts.isStringLiteral(key) ? key.text : undefined
      if (spelled === undefined) return undefined
      const value = literalJson(member.initializer, bindings, followed)
      if (value === undefined) return undefined
      rendered.push(`${JSON.stringify(spelled)}:${value}`)
    }
    return `{${rendered.join(",")}}`
  }
  return undefined
}

/**
 * Renders one taught field. A conditional renders both arms, because a site
 * that teaches one of two laws teaches both texts and an edit to either is the
 * event this wall exists to show.
 */
const render = (
  value: ts.Expression | undefined,
  bindings: Bindings,
): string => {
  if (value === undefined) return ABSENT
  const json = literalJson(value, bindings)
  if (json !== undefined) return json
  const { node } = resolve_(value, bindings, new Set())
  if (ts.isConditionalExpression(node)) {
    return `${render(node.whenTrue, bindings)} | ${render(node.whenFalse, bindings)}`
  }
  return NON_LITERAL
}

const renderNext = (
  value: ts.Expression | undefined,
  bindings: Bindings,
  emit: (line: string) => void,
): void => {
  if (value === undefined) {
    emit(`  next ${ABSENT}`)
    return
  }
  const { node: array, seen } = resolve_(value, bindings, new Set())
  if (!ts.isArrayLiteralExpression(array)) {
    emit(`  next ${NON_LITERAL}`)
    return
  }
  if (array.elements.length === 0) {
    emit("  next []")
    return
  }
  array.elements.forEach((element, index) => {
    if (!ts.isExpression(element)) {
      emit(`  next[${index}] ${NON_LITERAL}`)
      return
    }
    const { node: entry } = resolve_(element, bindings, seen)
    if (!ts.isObjectLiteralExpression(entry)) {
      emit(`  next[${index}] ${NON_LITERAL}`)
      return
    }
    emit(`  next[${index}].subject ${render(property(entry, "subject"), bindings)}`)
    emit(`  next[${index}].note ${render(property(entry, "note"), bindings)}`)
    const body = property(entry, "body")
    if (body !== undefined) emit(`  next[${index}].body ${render(body, bindings)}`)
  })
}

/**
 * Renders the taught-payload manifest over a tree of sources.
 *
 * `read` is passed in rather than reached for, so the same walk runs over the
 * working tree and over any other revision's bytes without the walk knowing
 * which it is looking at.
 */
export const renderTaughtPayloads = (
  files: ReadonlyArray<string>,
  read: (file: string) => string,
): string => {
  const out: Array<string> = [provenance.trimEnd(), authority.trimEnd()]
  const emit = (line: string): void => void out.push(line)
  for (const file of files) {
    const source = read(file)
    const parsed = ts.createSourceFile(file, source, ts.ScriptTarget.ESNext, true, ts.ScriptKind.TS)
    const bindings = bindingsOf(parsed)
    const payloads: Array<ts.ObjectLiteralExpression> = []
    const visit = (node: ts.Node): void => {
      if (
        ts.isObjectLiteralExpression(node)
        && property(node, PAYLOAD_MARKER) !== undefined
        && PAYLOAD_COMPANIONS.some((field) => property(node, field) !== undefined)
      ) {
        payloads.push(node)
      }
      ts.forEachChild(node, visit)
    }
    visit(parsed)
    payloads.forEach((payload, ordinal) => {
      emit(`${normalize(`${SOURCE_ROOT}/${file}`)}#${ordinal}`)
      for (const field of TAUGHT_FIELDS) {
        emit(`  ${field} ${render(property(payload, field), bindings)}`)
      }
      renderNext(property(payload, "next"), bindings, emit)
    })
  }
  return `${out.join("\n")}\n`
}

/** How many payloads a rendered manifest pins. */
export const countTaughtPayloads = (manifest: string): number =>
  manifest.split("\n").filter((line) => line.includes("#") && !line.startsWith("#")).length

/** Checks committed manifest bytes against a fresh walk. */
export const checkTaughtPayloads = (
  committed: string,
  rendered: string,
): TaughtPayloadCheck =>
  committed === rendered
    ? { ok: true, payloads: countTaughtPayloads(rendered) }
    : { ok: false, reason: "committed taught refusal payloads failed byte-identical rendering" }
