import { transportTerms as anchorsTerms } from "../src/internal/anchors.js"
import { transportTerms as cellsTerms } from "../src/internal/cells.js"
import { transportTerms as chaosTerms } from "../src/internal/chaos.js"
import { transportTerms as foldsTerms } from "../src/internal/folds.js"
import { transportTerms as lanesTerms } from "../src/internal/lanes.js"
import { transportTerms as natsTerms } from "../src/internal/nats.js"
import { transportTerms as pumpTerms } from "../src/internal/pump.js"
import { transportTerms as registersTerms } from "../src/internal/registers.js"
import { transportRefusalFor, type TransportTerms } from "../src/internal/transport.js"

/**
 * The transport spine's refusal corpus: every absence the spine can mint,
 * emitted by executing the spine over the adapters' own terms.
 *
 * The table is derived, never hand-listed — `adapters` below imports the same
 * `TransportTerms` records `internal/transport.ts` consumes, so an adapter
 * cannot drift out of the wall and a ninth adapter cannot be silently omitted
 * (`TransportSpine.test.ts` scans `src/internal` and fails on an absentee).
 *
 * Derivation alone cannot refute a homogenization — a table read from the
 * adapters agrees with the adapters by construction — so the emitted rows are
 * frozen in `fixtures/transport-refusals.ndjson` and regenerated byte-for-byte
 * by the wall, the same discipline `fixtures/envelopes.ndjson` runs under. The
 * committed bytes' authority is external to both sides: DEV-748's review dumped
 * all eight bindings at `14298c2` (before the spine existed) and at `963259d`
 * and diffed them byte-for-byte, so this corpus is anchored to the
 * pre-extraction behaviour, and every later drift reds.
 */

/** The cause every row is minted from, so `got` is deterministic. */
const PINNED_CAUSE = new Error("pinned transport cause")

/**
 * Each row's operations: one the adapter actually refuses on, and one it never
 * uses. The pair separates the terms that track the operation from the terms
 * that are fixed regardless of it.
 */
const OPERATIONS = ["connection.acquire", "some.other.operation"] as const

/** The adapters, in source order, each with the terms its module exports. */
export const adapters: ReadonlyArray<readonly [string, TransportTerms]> = [
  ["anchors", anchorsTerms],
  ["cells", cellsTerms],
  ["chaos", chaosTerms],
  ["folds", foldsTerms],
  ["lanes", lanesTerms],
  ["nats", natsTerms],
  ["pump", pumpTerms],
  ["registers", registersTerms],
]

/** One minted transport absence, flattened for byte comparison. */
export interface TransportRefusalRow {
  readonly adapter: string
  readonly operation: string
  readonly sort: string
  readonly kind: string
  readonly law: string
  readonly path: ReadonlyArray<string>
  readonly got: unknown
  readonly expected: unknown
  readonly next: ReadonlyArray<{ readonly subject: string; readonly note: string }>
}

/** The result of comparing corpus bytes with a fresh emission. */
export type TransportRefusalCheck =
  | { readonly ok: true }
  | { readonly ok: false; readonly reason: string }

const rows = (): ReadonlyArray<TransportRefusalRow> =>
  adapters.flatMap(([adapter, terms]) => {
    const refuse = transportRefusalFor(terms)
    return OPERATIONS.map((operation): TransportRefusalRow => {
      const minted = refuse(operation, PINNED_CAUSE)
      return {
        adapter,
        operation,
        sort: minted.sort,
        kind: minted.kind,
        law: minted.law,
        path: [...minted.path],
        got: minted.got,
        expected: minted.expected,
        next: minted.next.map((step) => ({ subject: step.subject, note: step.note })),
      }
    })
  })

/** Emits the deterministic NDJSON corpus, including its provenance line. */
export const generateTransportRefusals = (): string => [
  JSON.stringify({ provenance: "bun run generate:transport-refusals" }),
  ...rows().map((row) => JSON.stringify(row)),
  "",
].join("\n")

/** Checks that committed corpus bytes equal a fresh emission from the spine. */
export const checkTransportRefusals = (committed: string): TransportRefusalCheck =>
  committed === generateTransportRefusals()
    ? { ok: true }
    : {
      ok: false,
      reason: "committed transport-refusal corpus failed byte-identical regeneration",
    }
