#!/usr/bin/env python3
"""Render scratch/dev813/prose-inventory.md from census-out.json.

Run after scratch/dev813/extract.py, from the repository root."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
d=json.load(open(ROOT+"/scratch/dev813/census-out.json"))
LAW=re.compile(r'\b(c\d+_[a-z_0-9]+|f\d+_[a-z_0-9]+|at_most_one_landed_commit)\b')
REF=["clock-read","absence-trigger","unfenced-decide","last-writer-wins","unverified-read",
 "cross-sort-identifier","minted-identifier","ambient-query-input","forward-reference",
 "secret-carrier","absence-claim","past-mutation","off-writ-referent","closure-introspection",
 "anchored-resolve","unfilled-hole"]
out=[]
w=out.append
w("# DEV-813 prep: the prose-with-no-source inventory\n")
w("DRAFT. Generated by `scratch/dev813/extract.py` from")
w("`verify/kernel/projections/tools.schema.json` at sha256 `%s`.\n" % d["sha256"])
w("The model carries **zero** constructor-level and zero field-level docstrings")
w("(`verify/kernel/Kernel/Definitions.lean`, measured: 0 of 109 docstrings sit on a")
w("constructor). `Projections.Walk.docOf` calls `findDocString?` on the declaration")
w("name only, so `ProjectionAst.docs` carries one `DocSentence` per manifest name --")
w("22 rows, none of them a tool or a field. Every paragraph below therefore has no")
w("model source today and is review load the ticket must price.\n")
w("Counts: 8 tool descriptions, %d field descriptions, %d `$comment` paragraphs, %s words."
  % (len(d["field_descriptions"]), len(d["comments"]),
     sum(len(x["text"].split()) for x in d["tool_descriptions"]+d["field_descriptions"]+d["comments"])))
w("Each row is tagged with the fabric law it cites. A law name is a *reference* the")
w("model does carry -- the citation can be checked -- but the sentence around it is")
w("authored prose.\n")
w("## The 8 tool descriptions\n")
for t in d["tool_descriptions"]:
    w("### `%s`\n" % t["tool"])
    laws = t["laws"] or ["(no `f`/`c` law name; cites a discipline by phrase)"]
    w("Law cited: %s" % ", ".join("`%s`" % l for l in laws))
    hits=[r for r in REF if r in t["text"]]
    if hits: w("Refusal reasons named: %s" % ", ".join("`%s`" % h for h in hits))
    w("")
    w("> " + t["text"])
    w("")
w("## The %d field descriptions\n" % len(d["field_descriptions"]))
cur=None
for f in d["field_descriptions"]:
    tool=f["field"].rsplit(".",1)[0]
    if tool!=cur:
        cur=tool; w(""); w("### `%s`\n" % tool)
    laws=sorted(set(LAW.findall(f["text"])))
    hits=[r for r in REF if r in f["text"]]
    tag=""
    if laws: tag += "  [laws: %s]" % ", ".join(laws)
    if hits: tag += "  [refusals: %s]" % ", ".join(hits)
    w("- `%s`%s" % (f["field"].rsplit(".",1)[1], tag))
    w("  > " + f["text"])
w("")
w("## The 3 `$comment` paragraphs\n")
for c in d["comments"]:
    w("### `%s`\n" % (c["path"] or "/"))
    w("> " + c["text"])
    w("")
open(ROOT+"/scratch/dev813/prose-inventory.md","w").write("\n".join(out))
print("wrote", len(out), "lines")
