<#
Negative controls for scripts/lean-store.ps1. A store that cannot refuse
proves nothing: each control corrupts a scratch store entry in exactly one
way and requires the script to refuse with a nonzero exit and the named
message. Positives first, so a refusal is attributable to the corruption and
never to a broken fixture. Touches only a scratch directory - never the real
store under %USERPROFILE%\.foldlab.

Run:  pwsh -File scripts/lean-store-controls/run.ps1
It rewrites refusals.txt beside itself; commit the refreshed trace.
#>
$ErrorActionPreference = "Stop"
$script:failures = 0
$leanStore = Join-Path (Split-Path -Parent $PSScriptRoot) "lean-store.ps1"
$repoPkg = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) "verify\fabric-veil"
$scratch = Join-Path ([System.IO.Path]::GetTempPath()) "lean-store-controls"
$store = Join-Path $scratch "store"
$trace = Join-Path $PSScriptRoot "refusals.txt"

function New-ScratchTree([string]$Name, [switch]$AlterPins, [switch]$WithPackages) {
  $t = Join-Path $scratch $Name
  New-Item -ItemType Directory -Force -Path $t | Out-Null
  foreach ($f in "lean-toolchain", "lake-manifest.json", "setup-windows.ps1") {
    Copy-Item -LiteralPath (Join-Path $repoPkg $f) -Destination (Join-Path $t $f)
  }
  if ($AlterPins) { Add-Content -LiteralPath (Join-Path $t "lean-toolchain") -Value "# altered pin" }
  if ($WithPackages) {
    $manifest = Get-Content -LiteralPath (Join-Path $t "lake-manifest.json") -Raw | ConvertFrom-Json
    foreach ($dep in $manifest.packages) {
      $d = Join-Path (Join-Path $t ".lake\packages") $dep.name
      New-Item -ItemType Directory -Force -Path $d | Out-Null
      Set-Content -LiteralPath (Join-Path $d "stub.txt") -Value "stub for $($dep.name)"
    }
  }
  return $t
}

function Invoke-Control([string]$Label, [int]$WantExit, [string]$WantMatch, [string[]]$CallArgs) {
  $out = & pwsh -NoProfile -File $leanStore -StoreRoot $store @CallArgs 2>&1 | Out-String
  $code = $LASTEXITCODE
  $okExit = if ($WantExit -eq 0) { $code -eq 0 } else { $code -ne 0 }
  $okText = $out -match [regex]::Escape($WantMatch)
  $verdict = if ($okExit -and $okText) { "OK" } else { $script:failures++; "CONTROL FAILED" }
  $wanted = if ($WantExit -eq 0) { "0" } else { "nonzero" }
  Add-Content -LiteralPath $trace -Value @(
    "== $Label", "command: lean-store.ps1 $($CallArgs -join ' ')",
    "exit: $code (wanted $wanted)   must-contain: $WantMatch", $out.TrimEnd(), "verdict: $verdict", ""
  )
}

if (Test-Path -LiteralPath $scratch) { Remove-Item -LiteralPath $scratch -Recurse -Force }
New-Item -ItemType Directory -Force -Path $store | Out-Null
$treeA = New-ScratchTree "treeA" -WithPackages   # seed source
$treeB = New-ScratchTree "treeB"                 # attaches at the same key
$treeC = New-ScratchTree "treeC" -AlterPins      # different key, stale junction
$treeD = New-ScratchTree "treeD" -WithPackages   # real dir where a junction is expected
Set-Content -LiteralPath $trace -Value @(
  "Negative-control trace for scripts/lean-store.ps1.",
  "Generated by: pwsh -File scripts/lean-store-controls/run.ps1 (scratch store; no real store touched).", ""
)

Invoke-Control "positive: seed from a built tree" 0 "seeded" @("-Seed", $treeA)
Invoke-Control "positive: attach a second tree, same key" 0 "attached" @("-Tree", $treeB)
Invoke-Control "positive: re-run is idempotent" 0 "VERIFIED" @("-Tree", $treeB)

$key = (Get-ChildItem -LiteralPath $store -Directory | Select-Object -First 1).Name
$marker = Join-Path (Join-Path $store $key) ".complete"
$saved = Get-Content -LiteralPath $marker

Remove-Item -LiteralPath $marker
Invoke-Control "control: completion marker deleted" 1 "no completion marker" @("-Tree", $treeB)
Set-Content -LiteralPath $marker -Value @("0000deadbeef")
Invoke-Control "control: completion marker key altered" 1 "does not certify these pins" @("-Tree", $treeB)
Set-Content -LiteralPath $marker -Value $saved
Invoke-Control "positive: marker restored, verification recovers" 0 "VERIFIED" @("-Tree", $treeB)

# Stale junction: treeC's pins compute a different key, but its junction
# still points at treeA's entry - the post-pin-move hazard.
New-Item -ItemType Directory -Force -Path (Join-Path $treeC ".lake") | Out-Null
New-Item -ItemType Junction -Path (Join-Path $treeC ".lake\packages") -Value (Join-Path (Join-Path $store $key) "packages") | Out-Null
Invoke-Control "control: junction target does not match the tree's pins" 1 "junction target does not match" @("-Tree", $treeC)

Invoke-Control "control: real directory where a junction is expected (key already in store)" 1 "real directory" @("-Tree", $treeD)

Invoke-Control "control: refuse to seed over an existing store entry" 1 "refusing to overwrite" @("-Seed", $treeD)

# Real directory at a key the store has never seen: the refusal must offer
# the -Seed migration command and must not migrate on its own.
$treeE = New-ScratchTree "treeE" -AlterPins -WithPackages
Invoke-Control "control: real directory at a fresh key offers -Seed, no auto-migration" 1 "-Seed" @("-Tree", $treeE)

Add-Content -LiteralPath $trace -Value "result: $(if ($script:failures -eq 0) { 'ALL CONTROLS HELD' } else { "$script:failures CONTROL(S) FAILED" })"
Get-Content -LiteralPath $trace | Write-Host
exit $(if ($script:failures -eq 0) { 0 } else { 1 })
